/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 board.glb 
Author: M.Reslan (https://sketchfab.com/mreslan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/messy-tack-board-da1301f7148f421698d6b9dc1858d45b
Title: Messy Tack Board
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Board(props) {
  const { nodes, materials } = useGLTF('/models/board.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-32.121, -13.428, 1.629]} rotation={[0, 0, -0.086]} scale={0.133}>
        <mesh geometry={nodes['Object001_Material_#1_0'].geometry} material={materials.Material_1} position={[168.642, -153.031, 0]} />
      </group>
      <group position={[-7.953, 7.624, 1.801]} scale={0.133}>
        <mesh geometry={nodes['Object002_Material_#1_0'].geometry} material={materials.Material_1} position={[51.373, -153.031, 0]} />
      </group>
      <group position={[19.865, -2.05, 1.839]} rotation={[0, 0, -0.045]} scale={0.182}>
        <mesh geometry={nodes['Object003_Material_#1_0'].geometry} material={materials.Material_1} position={[-11.855, -153.031, 0]} />
      </group>
      <group position={[30.468, -21.352, 3.157]} rotation={[0, 0, -Math.PI / 9]} scale={0.062}>
        <mesh geometry={nodes['Object004_Material_#1_0'].geometry} material={materials.Material_1} position={[-70.376, -153.031, 0]} />
      </group>
      <group position={[-32.741, 11.254, 1.788]} rotation={[0, 0, 0.072]} scale={0.141}>
        <mesh geometry={nodes['Object005_Material_#1_0'].geometry} material={materials.Material_1} position={[-122.928, -153.031, 0]} />
      </group>
      <group position={[-32.835, -2.616, 1.869]} rotation={[0, 0, 0.044]} scale={0.133}>
        <mesh geometry={nodes['Object007_Material_#1_0'].geometry} material={materials.Material_1} position={[162.474, -65.008, 0]} />
      </group>
      <group position={[1.294, 1.329, 1.826]} rotation={[0, 0, 0.028]} scale={0.133}>
        <mesh geometry={nodes['Object008_Material_#1_0'].geometry} material={materials.Material_1} position={[93.69, -65.008, 0]} />
      </group>
      <group position={[-21.999, -9.501, 1.868]} rotation={[0, 0, 0.033]} scale={0.172}>
        <mesh geometry={nodes['Object009_Material_#1_0'].geometry} material={materials.Material_1} position={[27.915, -65.008, 0]} />
      </group>
      <group position={[-13.66, 7.043, 1.808]} rotation={[0, 0, -0.322]} scale={0.149}>
        <mesh geometry={nodes['Object010_Material_#1_0'].geometry} material={materials.Material_1} position={[-30.463, -65.008, 0]} />
      </group>
      <group position={[7.675, -10.293, 1.839]} rotation={[0, 0, 0.106]} scale={0.159}>
        <mesh geometry={nodes['Object011_Material_#1_0'].geometry} material={materials.Material_1} position={[-88.815, -65.008, 0]} />
      </group>
      <group position={[24.367, 6.501, 1.829]} rotation={[0, 0, 0.174]} scale={0.133}>
        <mesh geometry={nodes['Object012_Material_#1_0'].geometry} material={materials.Material_1} position={[-152.766, -65.008, 0]} />
      </group>
      <group position={[-17.326, 8.358, 1.801]} scale={0.133}>
        <mesh geometry={nodes['Object013_Material_#1_0'].geometry} material={materials.Material_1} position={[109.651, -153.031, 0]} />
      </group>
      <group position={[-11.581, -8.136, 1.391]} rotation={[0.023, 0, 0.011]} scale={0.128}>
        <mesh geometry={nodes['Object015_Material_#1_0'].geometry} material={materials.Material_1} position={[164.085, 22.152, 0]} />
      </group>
      <group position={[-2.077, -11.436, 1.783]} scale={0.16}>
        <mesh geometry={nodes['Object016_Material_#1_0'].geometry} material={materials.Material_1} position={[99.698, 22.152, 0]} />
      </group>
      <group position={[-24.362, 16.01, 3.112]} rotation={[0, 0, 0.056]} scale={0.08}>
        <mesh geometry={nodes['Object017_Material_#1_0'].geometry} material={materials.Material_1} position={[30.24, 22.152, 0]} />
      </group>
      <group position={[14.974, 9.556, 1.83]} rotation={[0, 0, 0.052]} scale={0.133}>
        <mesh geometry={nodes['Object018_Material_#1_0'].geometry} material={materials.Material_1} position={[-46.603, 22.152, 0]} />
      </group>
      <group position={[3.123, 11.734, 1.79]} rotation={[0, 0, 1.584]} scale={0.202}>
        <mesh geometry={nodes['Object019_Material_#1_0'].geometry} material={materials.Material_1} position={[-105.892, 22.152, 0]} />
      </group>
      <group position={[30.344, 12.483, 1.779]} rotation={[0, 0, Math.PI / 2]} scale={0.171}>
        <mesh geometry={nodes['Object020_Material_#1_0'].geometry} material={materials.Material_1} position={[-163.563, 22.152, 0]} />
      </group>
      <group position={[33.14, -1.053, 1.86]} scale={0.1}>
        <mesh geometry={nodes['Object021_Material_#1_0'].geometry} material={materials.Material_1} position={[-86.495, 95.366, 0]} />
      </group>
      <group position={[23.33, -13.543, 1.786]} scale={0.1}>
        <mesh geometry={nodes['Object022_Material_#1_0'].geometry} material={materials.Material_1} position={[-6.018, 95.366, 0]} />
      </group>
      <group position={[31.748, -13.711, 1.788]} scale={0.1}>
        <mesh geometry={nodes['Object023_Material_#1_0'].geometry} material={materials.Material_1} position={[74.869, 95.366, 0]} />
      </group>
      <group position={[30.989, -7.395, 1.806]} scale={0.1}>
        <mesh geometry={nodes['Object024_Material_#1_0'].geometry} material={materials.Material_1} position={[156.146, 95.366, 0]} />
      </group>
      <group position={[-33.03, 16.315, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line001_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line001_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[35.284, -21.92, 3.09]} rotation={[0, 0, -0.075]} scale={0.08}>
        <mesh geometry={nodes['Object047_Material_#1_0'].geometry} material={materials.Material_1} position={[30.24, 22.152, 0]} />
      </group>
      <group position={[11.875, 3.277, 1.783]} rotation={[0, 0, -0.323]} scale={0.128}>
        <mesh geometry={nodes['Object048_Material_#1_0'].geometry} material={materials.Material_1} position={[164.085, 22.152, 0]} />
      </group>
      <group position={[-6.337, -0.66, 1.566]} rotation={[0, 0, 0.081]} scale={0.133}>
        <mesh geometry={nodes['Object049_Material_#1_0'].geometry} material={materials.Material_1} position={[168.642, -153.031, 0]} />
      </group>
      <group position={[29.619, 0.625, 1.792]} rotation={[0, 0, 0.033]} scale={0.172}>
        <mesh geometry={nodes['Object050_Material_#1_0'].geometry} material={materials.Material_1} position={[27.915, -65.008, 0]} />
      </group>
      <group position={[17.415, -9.219, 1.782]} rotation={[0, 0, 0.066]} scale={0.08}>
        <mesh geometry={nodes['Object051_Material_#1_0'].geometry} material={materials.Material_1} position={[30.24, 22.152, 0]} />
      </group>
      <group position={[33.903, 4.776, 1.782]} rotation={[0, 0, -0.073]} scale={0.08}>
        <mesh geometry={nodes['Object052_Material_#1_0'].geometry} material={materials.Material_1} position={[30.24, 22.152, 0]} />
      </group>
      <group position={[7.033, 0.379, 1.775]} rotation={[0, 0, -0.012]} scale={0.133}>
        <mesh geometry={nodes['Object053_Material_#1_0'].geometry} material={materials.Material_1} position={[162.474, -65.008, 0]} />
      </group>
      <group position={[-27.583, 7.332, 1.783]} rotation={[0, 0, -0.035]} scale={0.16}>
        <mesh geometry={nodes['Object054_Material_#1_0'].geometry} material={materials.Material_1} position={[99.698, 22.152, 0]} />
      </group>
      <group position={[-23.388, -4.569, 1.841]} rotation={[0, 0, 0.068]} scale={0.182}>
        <mesh geometry={nodes['Object055_Material_#1_0'].geometry} material={materials.Material_1} position={[-11.855, -153.031, 0]} />
      </group>
      <group position={[-12.321, 13.328, 1.783]} rotation={[0, 0, -0.019]} scale={0.128}>
        <mesh geometry={nodes['Object056_Material_#1_0'].geometry} material={materials.Material_1} position={[164.085, 22.152, 0]} />
      </group>
      <group position={[-14.914, -2.304, 1.782]} rotation={[0, 0, 0.094]} scale={0.08}>
        <mesh geometry={nodes['Object057_Material_#1_0'].geometry} material={materials.Material_1} position={[30.24, 22.152, 0]} />
      </group>
      <group position={[-28.858, -12.682, 1.797]} rotation={[0, 0, 1.584]} scale={0.202}>
        <mesh geometry={nodes['Object058_Material_#1_0'].geometry} material={materials.Material_1} position={[-105.892, 22.152, 0]} />
      </group>
      <group position={[-17.485, 12.905, 1.776]} rotation={[0, 0, 1.584]} scale={0.202}>
        <mesh geometry={nodes['Object059_Material_#1_0'].geometry} material={materials.Material_1} position={[-105.892, 22.152, 0]} />
      </group>
      <group position={[-13.392, -11.916, 1.685]} rotation={[0, 0, -0.033]} scale={0.133}>
        <mesh geometry={nodes['Object060_Material_#1_0'].geometry} material={materials.Material_1} position={[-46.603, 22.152, 0]} />
      </group>
      <group position={[13.538, -14.535, 1.802]} rotation={[0, 0, -0.003]} scale={0.062}>
        <mesh geometry={nodes['Object061_Material_#1_0'].geometry} material={materials.Material_1} position={[-70.376, -153.031, 0]} />
      </group>
      <group position={[-19.657, 12.71, 2.227]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.029}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line002_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line002_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-18.695, 2.91, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line003_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line003_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-27.915, 1.973, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line004_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line004_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[10.858, 16.011, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line005_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line005_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-4.781, 15.877, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line006_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line006_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-15.273, 13.003, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line007_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line007_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-9.12, 10.997, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line008_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line008_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[13.476, -12.064, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line009_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line009_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[4.388, -16.877, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line010_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line010_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[10.942, -3.776, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line011_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line011_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[14.822, 4.981, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line012_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line012_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[14.29, -8.789, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line013_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line013_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[24.921, -9.19, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line014_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line014_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-6.894, 15.208, 2.223]} rotation={[1.719, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line015_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line015_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[21.318, 16.278, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line016_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line016_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-14.575, -4.1, 2.322]} rotation={[1.594, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line017_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line017_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[20.187, 10.797, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line018_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line018_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[18.719, 14.74, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line019_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line019_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[10.768, 14.406, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line020_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line020_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-10.954, -0.634, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line021_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line021_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[37.11, 17.548, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line022_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line022_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[23.811, 17.347, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line023_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line023_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-3.378, 3.103, 1.83]} rotation={[0, 0, -1.56]}>
        <mesh geometry={nodes['Object062_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 13.381, 0]} />
      </group>
      <group position={[0.042, -4.93, 1.792]}>
        <mesh geometry={nodes['Object063_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 14.566, 0]} />
      </group>
      <group position={[-21.301, 3.303, 1.801]} rotation={[0, 0, 0.173]}>
        <mesh geometry={nodes['Object064_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 15.912, 0]} />
      </group>
      <group position={[-6.406, -14.939, 1.791]} rotation={[0, 0, 1.543]} scale={0.711}>
        <mesh geometry={nodes['Object065_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 17.378, 0]} />
      </group>
      <group position={[-5.572, 13.205, 1.815]}>
        <mesh geometry={nodes['Object066_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 18.647, 0]} />
      </group>
      <group position={[29.157, -1.961, 1.946]} rotation={[0, 0, -1.56]} scale={0.552}>
        <mesh geometry={nodes['Object067_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 13.381, 0]} />
      </group>
      <group position={[37.213, -1.707, 1.946]} rotation={[0, 0, -1.56]} scale={0.552}>
        <mesh geometry={nodes['Object068_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 13.381, 0]} />
      </group>
      <group position={[-31.706, -8.346, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line024_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line024_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-22.21, -3.15, 2.329]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line025_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line025_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[30.034, -18.818, 3.186]} rotation={[0, 0, 0.188]} scale={[0.789, 0.665, 1]}>
        <mesh geometry={nodes['Object069_Material_#1_0'].geometry} material={materials.Material_1} position={[-7.975, 18.647, 0]} />
      </group>
      <group position={[23.401, -11.131, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line026_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line026_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[31.893, -5.046, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line027_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line027_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[31.72, -11.301, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line028_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line028_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[5.966, 2.33, 1.946]} rotation={[0, 0, -1.506]} scale={0.722}>
        <mesh geometry={nodes['Object070_Material_#1_0'].geometry} material={materials.Material_1} position={[-9.418, 13.381, 0]} />
      </group>
      <group position={[-24.649, 18.824, 3.611]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line029_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line029_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[35.315, -19.006, 3.624]} rotation={[1.605, -0.097, 0.342]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line030_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line030_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-6.35, 16.46, 2.223]} rotation={[1.557, -0.102, -0.132]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line031_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line031_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[-7.768, 16.115, 2.223]} rotation={[1.71, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line032_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line032_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[12.992, 15.591, 2.223]} rotation={[Math.PI / 2, -0.103, 0]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line033_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line033_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <group position={[20.047, 12.13, 2.223]} rotation={[1.537, -0.097, -0.333]} scale={0.033}>
        <group position={[3.58, 5.262, 0]}>
          <mesh geometry={nodes.Line034_PinPlastic_0.geometry} material={materials.PinPlastic} />
          <mesh geometry={nodes.Line034_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
      <mesh geometry={nodes['Box001_Material_#1_0'].geometry} material={materials.Material_1} />
    </group>
  )
}

useGLTF.preload('/models/board.glb')

export default Board;
