/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 candles_set.glb 
Author: shuvalov.di (https://sketchfab.com/shuvalov.di)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/candles-set-f09212756bc94764a8bcfcd3c7e38f8e
Title: Candles set
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

function Candles(props) {
	const group = React.useRef();
	const { nodes, materials, animations } = useGLTF("/models/candles_set.glb");
	const { actions } = useAnimations(animations, group);
	// console.log(actions);
	useEffect(() => {
		actions["Animation"].play();
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null} scale={2.5}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
					<group name="root">
						<group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
							<group name="candle_1_0" position={[0.055, 0.092, 0.005]} rotation={[Math.PI / 2, 0, -0.969]} scale={0.238}>
								<mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Candle_1} />
							</group>
							<group name="candle_wick_1_1" position={[0.056, 0.172, 0]} rotation={[Math.PI / 2, 0, -0.969]} scale={0.238}>
								<mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Candle_1} />
							</group>
							<group name="candle_2_2" position={[-0.035, 0.057, -0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.238}>
								<mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Candle_2} />
							</group>
							<group name="candle_wick_2_3" position={[-0.037, 0.103, -0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.238}>
								<mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Candle_2} />
							</group>
							<group name="candle_3_4" position={[-0.054, 0.043, 0.071]} rotation={[Math.PI / 2, 0, 0.093]} scale={0.238}>
								<mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Candle_3} />
							</group>
							<group name="candle_wick_3_5" position={[-0.056, 0.071, 0.068]} rotation={[Math.PI / 2, 0, 0.093]} scale={0.238}>
								<mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Candle_3} />
							</group>
							<group name="Flame_3_6" position={[-0.056, 0.073, 0.068]} rotation={[0, -0.093, 0]} scale={[1.014, 1.088, 1.014]}>
								<mesh
									name="mesh_6"
									geometry={nodes.mesh_6.geometry}
									material={materials.Flame}
									morphTargetDictionary={nodes.mesh_6.morphTargetDictionary}
									morphTargetInfluences={nodes.mesh_6.morphTargetInfluences}
								/>
							</group>
							<group name="Flame_2_7" position={[-0.037, 0.104, -0.046]} scale={1.131}>
								<mesh
									name="mesh_7"
									geometry={nodes.mesh_7.geometry}
									material={materials.Flame}
									morphTargetDictionary={nodes.mesh_7.morphTargetDictionary}
									morphTargetInfluences={nodes.mesh_7.morphTargetInfluences}
								/>
							</group>
							<group name="Flame_1_8" position={[0.056, 0.177, 0.001]} rotation={[0, 0.969, 0]}>
								<mesh
									name="mesh_8"
									geometry={nodes.mesh_8.geometry}
									material={materials.Flame}
									morphTargetDictionary={nodes.mesh_8.morphTargetDictionary}
									morphTargetInfluences={nodes.mesh_8.morphTargetInfluences}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/candles_set.glb");

export default Candles;
