/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 globe.glb 
Author: Solar Impulse (https://sketchfab.com/solarimpulse)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-impulse-flight-path-298e1ac1fdb048e892d036d588d4322c
Title: Solar Impulse Flight Path
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Globe(props) {
  const { nodes, materials } = useGLTF('/models/globe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/globe.glb')

export default Globe;
