/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pianoShelf.glb 
Author: eventdesignws (https://sketchfab.com/eventdesignws)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ground-steak-konser-outdoor-398a16e01392417c85608de85a3d3872
Title: ground steak konser outdoor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function PianoShelf(props) {
  const { nodes, materials } = useGLTF('/models/pianoShelf.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Metal_Rough} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.logo_ws_design_colour__01} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.wp7470205} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/pianoShelf.glb')

export default PianoShelf;
