/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shelf.glb 
Author: alleedubureau (https://sketchfab.com/alleedubureau)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/armoire-basse-sur-patins-alto-d382b916619a48b6a24c806a61c3ce07
Title: ARMOIRE BASSE SUR PATINS ALTO
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Shelf(props) {
  const { nodes, materials } = useGLTF('/models/shelf.glb')
  return (
    <group {...props} dispose={null} scale={1.7}>
      <mesh geometry={nodes['brmc_alto_d3_armoire_base_brmcbasicsbrmcnitechf;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcnitechf_auto_xzx_yz_rotate_0_0_0} position={[0, -0.301, 0]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_fond_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0, -0.116, 0]} scale={[1, 0.487, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_fond_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_1'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.387, -0.116, 0]} scale={[1.495, 0.487, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_joue_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0, -0.116, 0]} scale={[1, 0.487, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_joue_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_1'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.98, -0.116, 0]} scale={[1, 0.487, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_joue_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_2'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.396, -0.116, 0]} scale={[0.999, 0.487, 0.957]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_patin_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.932, 0, 0.04]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_patin_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_1'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.932, 0, 0.392]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_patin_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_2'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.068, 0, 0.392]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_patin_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_3'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.5, 0, 0.23]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_patin_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0_4'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[0.068, 0, 0.04]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_porte_brmcbasicsbrmcnitechf;_auto_xzx_yz;_rotate_0_0_90_0'].geometry} material={materials.brmcbasicsbrmcnitechf_auto_xzx_yz_rotate_0_0_90} position={[0.004, -0.113, 0]} scale={[0.993, 0.483, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_porte_cle_brmcbasicsbrmcchromec;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcchromec_auto_xzx_yz_rotate_0_0_0} position={[-0.001, -0.645, 0]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_porte_poignee_brmcbasicsbrmcplastiqueg;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcplastiqueg_auto_xzx_yz_rotate_0_0_0} position={[-0.001, -0.645, 0]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_tablette_brmcbasicsbrmcnitechf;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcnitechf_auto_xzx_yz_rotate_0_0_0} position={[0.414, 0.394, 0.384]} scale={[1.495, 1, 1]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_tablette_brmcbasicsbrmcnitechf;_auto_xzx_yz;_rotate_0_0_0_0_1'].geometry} material={materials.brmcbasicsbrmcnitechf_auto_xzx_yz_rotate_0_0_0} position={[0.018, 0.394, 0.384]} />
      <mesh geometry={nodes['brmc_alto_d3_armoire_top_brmcbasicsbrmcnitechf;_auto_xzx_yz;_rotate_0_0_0_0'].geometry} material={materials.brmcbasicsbrmcnitechf_auto_xzx_yz_rotate_0_0_0} position={[0, -1, 0]} />
    </group>
  )
}

useGLTF.preload('/models/shelf.glb')

export default Shelf;
