/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tv_shelf.glb 
Author: kolpakov.k99 (https://sketchfab.com/kolpakov.k99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-shelf-4b598177d8814fcd8f23e40933655b07
Title: TV Shelf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function TvShelf(props) {
  const { nodes, materials } = useGLTF('/models/tv_shelf.glb')
  return (
    <group {...props} dispose={null} scale={1.5}>
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_31.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_33.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_71.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_89.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_91.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_93.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_97.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_99.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/models/tv_shelf.glb')
export default TvShelf;

