/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vinylPlayer.glb 
Author: TemmieTim (https://sketchfab.com/TemmieTim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/turntable-ion-audio-vinyl-transport-c7aa526b201e41ad8ae67bf3806cb2e6
Title: Turntable ION Audio Vinyl Transport
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function VinylPlayer(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/vinylPlayer.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(() => {
    actions['DiscPlate_low|DiscPlate_lowAction']?.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="014f6427026b40be85919a5cba0ed7a3fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="DiscPlate_low" position={[0, 7.915, 4.481]} rotation={[-Math.PI / 2, 0, 1.904]} scale={100}>
                  <mesh name="DiscPlate_low_Discplate_MAT_0" geometry={nodes.DiscPlate_low_Discplate_MAT_0.geometry} material={materials.Discplate_MAT} />
                </group>
                <group name="Roter_low" position={[0, 6.645, 4.481]} rotation={[-Math.PI / 2, 0, 1.904]} scale={100}>
                  <mesh name="Roter_low_TurnTable_Detail_MAT_0" geometry={nodes.Roter_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
                <group name="Needle_low_low" position={[-8.845, 8.591, -11.323]} rotation={[-1.57, 0.001, -0.476]} scale={100}>
                  <mesh name="Needle_low_low_TurnTable_Detail_MAT_0" geometry={nodes.Needle_low_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
                <group name="Box_Top_low" position={[-13, 5.786, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Box_Top_low_TurnBox_MAT_0" geometry={nodes.Box_Top_low_TurnBox_MAT_0.geometry} material={materials.TurnBox_MAT} />
                  <mesh name="Box_Top_low_TurnTable_Detail_MAT_0" geometry={nodes.Box_Top_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                  <mesh name="Box_Top_low_Decals_0" geometry={nodes.Box_Top_low_Decals_0.geometry} material={materials.Decals} />
                </group>
                <group name="Box_Bottom_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Box_Bottom_low_TurnBox_MAT_0" geometry={nodes.Box_Bottom_low_TurnBox_MAT_0.geometry} material={materials.TurnBox_MAT} />
                  <mesh name="Box_Bottom_low_TurnTable_Detail_MAT_0" geometry={nodes.Box_Bottom_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                  <mesh name="Box_Bottom_low_Decals_0" geometry={nodes.Box_Bottom_low_Decals_0.geometry} material={materials.Decals} />
                </group>
                <group name="Pin_low" position={[0, 7.539, 4.481]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Pin_low_TurnTable_Detail_MAT_0" geometry={nodes.Pin_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
                <group name="Dial_low" position={[5.546, 5.875, -14.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Dial_low_TurnTable_Detail_MAT_0" geometry={nodes.Dial_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
                <group name="Handle_low" position={[13.331, 4.624, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Handle_low_TurnTable_Detail_MAT_0" geometry={nodes.Handle_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
                <group name="Holder_low" position={[4.179, 6.085, -11.323]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Holder_low_TurnTable_Detail_MAT_0" geometry={nodes.Holder_low_TurnTable_Detail_MAT_0.geometry} material={materials.TurnTable_Detail_MAT} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/vinylPlayer.glb')

export default VinylPlayer;
