/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vinyl.glb 
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vinyls-3-4b9e9358335e4e0aa3aab21d989960af
Title: VINYLS 3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Vinyl(props) {
  const { nodes, materials } = useGLTF('/models/vinyl.glb')
  return (
    <group {...props} dispose={null} scale={0.6}>
      <group position={[0.012, 0.157, 0.161]} rotation={[Math.PI / 2, 0.061, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['cover.103']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.019, 0.157, 0.161]} rotation={[Math.PI / 2, 0.041, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials['cover.104']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.025, 0.157, 0.161]} rotation={[Math.PI / 2, 0.038, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['cover.105']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.03, 0.157, 0.161]} rotation={[Math.PI / 2, 0.029, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['cover.106']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.036, 0.157, 0.17]} rotation={[Math.PI / 2, 0.039, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['cover.107']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.046, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials['cover.108']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.051, 0.157, 0.168]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['cover.109']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.057, 0.157, 0.164]} rotation={[Math.PI / 2, 0.016, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['cover.110']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.064, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['cover.111']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.074, 0.157, 0.154]} rotation={[Math.PI / 2, 0.039, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials['cover.112']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.08, 0.157, 0.161]} rotation={[Math.PI / 2, 0.05, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['cover.113']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.089, 0.157, 0.161]} rotation={[Math.PI / 2, 0.081, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials['cover.114']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.094, 0.157, 0.161]} rotation={[Math.PI / 2, 0.077, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_40.geometry} material={materials['cover.115']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.099, 0.157, 0.169]} rotation={[Math.PI / 2, 0.069, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_43.geometry} material={materials['cover.116']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.105, 0.157, 0.161]} rotation={[Math.PI / 2, 0.064, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['cover.117']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.113, 0.157, 0.166]} rotation={[Math.PI / 2, 0.048, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials['cover.118']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.119, 0.157, 0.161]} rotation={[Math.PI / 2, 0.033, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials['cover.119']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.125, 0.157, 0.16]} rotation={[Math.PI / 2, 0.024, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_55.geometry} material={materials['cover.120']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.133, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials['cover.121']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.137, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_61.geometry} material={materials['cover.122']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.142, 0.157, 0.167]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_64.geometry} material={materials['cover.123']} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.152, 0.157, 0.163]} rotation={[Math.PI / 2, 0.036, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_67.geometry} material={materials['cover.124']} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.156, 0.157, 0.204]} rotation={[Math.PI / 2, 0.039, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials['cover.125']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.164, 0.157, 0.161]} rotation={[Math.PI / 2, 0.055, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['cover.126']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.171, 0.157, 0.158]} rotation={[Math.PI / 2, 0.073, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials['cover.127']} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.179, 0.157, 0.161]} rotation={[Math.PI / 2, 0.056, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_79.geometry} material={materials['cover.128']} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.183, 0.157, 0.161]} rotation={[Math.PI / 2, 0.056, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_82.geometry} material={materials['cover.129']} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.196, 0.157, 0.168]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials['cover.130']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.2, 0.157, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_88.geometry} material={materials['cover.131']} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.204, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_91.geometry} material={materials['cover.132']} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.208, 0.157, 0.165]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_94.geometry} material={materials['cover.133']} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.218, 0.157, 0.161]} rotation={[Math.PI / 2, 0.034, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_97.geometry} material={materials['cover.134']} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.223, 0.157, 0.161]} rotation={[Math.PI / 2, 0.04, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_100.geometry} material={materials['cover.135']} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.229, 0.157, 0.166]} rotation={[Math.PI / 2, 0.05, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_103.geometry} material={materials['cover.136']} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.233, 0.157, 0.161]} rotation={[Math.PI / 2, 0.054, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_106.geometry} material={materials['cover.137']} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.239, 0.157, 0.161]} rotation={[Math.PI / 2, 0.047, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_109.geometry} material={materials['cover.138']} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.244, 0.157, 0.161]} rotation={[Math.PI / 2, 0.039, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_112.geometry} material={materials['cover.139']} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.254, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_115.geometry} material={materials['cover.140']} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.258, 0.157, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_118.geometry} material={materials['cover.141']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.265, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_121.geometry} material={materials['cover.142']} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.268, 0.157, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_124.geometry} material={materials['cover.143']} />
        <mesh geometry={nodes.Object_125.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.276, 0.157, 0.182]} rotation={[Math.PI / 2, 0.022, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_127.geometry} material={materials['cover.144']} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.285, 0.157, 0.164]} rotation={[Math.PI / 2, 0.053, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_130.geometry} material={materials['cover.145']} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.291, 0.157, 0.161]} rotation={[Math.PI / 2, 0.051, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_133.geometry} material={materials['cover.146']} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.296, 0.157, 0.161]} rotation={[Math.PI / 2, 0.053, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_136.geometry} material={materials['cover.147']} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.308, 0.157, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_139.geometry} material={materials['cover.148']} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.313, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_142.geometry} material={materials['cover.149']} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.32, 0.157, 0.155]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_145.geometry} material={materials['cover.150']} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.324, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_148.geometry} material={materials['cover.151']} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.328, 0.157, 0.21]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_151.geometry} material={materials['cover.152']} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.335, 0.157, 0.161]} rotation={[Math.PI / 2, 0.017, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_154.geometry} material={materials['cover.153']} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.345, 0.157, 0.161]} rotation={[Math.PI / 2, 0.055, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_157.geometry} material={materials['cover.154']} />
        <mesh geometry={nodes.Object_158.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.353, 0.157, 0.161]} rotation={[Math.PI / 2, 0.082, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_160.geometry} material={materials['cover.155']} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.359, 0.157, 0.159]} rotation={[Math.PI / 2, 0.066, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_163.geometry} material={materials['cover.156']} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.366, 0.157, 0.161]} rotation={[Math.PI / 2, 0.05, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_166.geometry} material={materials['cover.157']} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.373, 0.157, 0.168]} rotation={[Math.PI / 2, 0.033, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_169.geometry} material={materials['cover.158']} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.382, 0.157, 0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_172.geometry} material={materials['cover.159']} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.39, 0.157, 0.175]} rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_175.geometry} material={materials['cover.160']} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.398, 0.157, 0.159]} rotation={[Math.PI / 2, 0.055, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_178.geometry} material={materials['cover.161']} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.407, 0.157, 0.161]} rotation={[Math.PI / 2, 0.085, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_181.geometry} material={materials['cover.162']} />
        <mesh geometry={nodes.Object_182.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.25, 0.002, 0.58]} rotation={[0, -0.579, 0]}>
        <mesh geometry={nodes.Object_184.geometry} material={materials['cover.163']} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.351, 0.002, 0.646]} rotation={[-Math.PI, -0.666, -Math.PI]}>
        <mesh geometry={nodes.Object_187.geometry} material={materials.vinyl} />
        <mesh geometry={nodes.Object_189.geometry} material={materials['label_front.002']} />
        <mesh geometry={nodes.Object_190.geometry} material={materials['label_back.002']} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.label_side} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/vinyl.glb')
export default Vinyl;