/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cymbal.glb 
Author: Wazahole (https://sketchfab.com/Wazahole)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cymbal-sabian-532e265c4c794282b47833277ee3c25e
Title: Cymbal Sabian
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Cymbal(props) {
  const { nodes, materials } = useGLTF('/models/cymbal.glb')
  return (
    <group {...props} dispose={null} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Sabian_01} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Sabian_02} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cymbal.glb')

export default Cymbal;
