/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 drumsticks.glb 
Author: Kamil.Fujarski (https://sketchfab.com/Kamil.Fujarski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drumsticks-610a13ddadf14d2cb52111d4f0ca93fa
Title: Drumsticks
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Drumsticks(props) {
	const { nodes, materials } = useGLTF("/models/drumsticks.glb");
	return (
		<group {...props} dispose={null} scale={1}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material_001} rotation={[-Math.PI / 2, 0, 0]} scale={0.2} />
					<mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Material_001} rotation={[-Math.PI / 2, 0, 0]} scale={0.2} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/drumsticks.glb");

export default Drumsticks;
