/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitarAmp.glb 
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitar-amplifier-be36a541b49e4187966ba83a50a24138
Title: Guitar Amplifier
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { exp } from "three/tsl";

function GuitarAmp(props) {
	const { nodes, materials } = useGLTF("/models/guitarAmp.glb");
	return (
		<group {...props} dispose={null} scale={0.07}>
			<mesh geometry={nodes.Object_2.geometry} material={materials.Orange_Guitar_Amplifier} rotation={[-Math.PI / 2, 0, 0]} />
		</group>
	);
}

useGLTF.preload("/models/guitarAmp.glb");

export default GuitarAmp;
