/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitarStand.glb 
Author: diabeticspoon92 (https://sketchfab.com/diatbeticspoon92)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitar-stand-71aaf9016ab3470fbd256027050137ee
Title: Guitar & Stand
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function GuitarStand(props) {
	const { nodes, materials } = useGLTF("/models/guitarStand.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group position={[3.882, 0, 1.503]} rotation={[0, 0, 0]}>
					<mesh geometry={nodes.guitar_stand_geo_01_mat_guitar_stand_01_0.geometry} material={materials.mat_guitar_stand_01} />
					<mesh geometry={nodes.guitar_geo_01_Mat_guitar_0.geometry} material={materials.Mat_guitar} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/guitarStand.glb");
export default GuitarStand;
