/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 microphone.glb 
Author: FatWasHere (https://sketchfab.com/fathin880)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/standing-microphone-0fb5da6bfe424f0ab6b447d431db9fab
Title: Standing Microphone
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Mic(props) {
	const { nodes, materials } = useGLTF("/models/microphone.glb");
	return (
		<group {...props} dispose={null}>
			<group position={[-12.717, 22.789, -17.673]} scale={0.041}>
				<mesh geometry={nodes.Object_24.geometry} material={materials["case_metal.001"]} />
				<mesh geometry={nodes.Object_25.geometry} material={materials["ALUMINIUM.073"]} />
			</group>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials["hitam.002"]}
				position={[-12.531, 22.844, -17.673]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.142}
			/>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials.base}
				position={[-12.521, 22.595, -17.673]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.019}
			/>
			<mesh
				geometry={nodes.Object_8.geometry}
				material={materials.hitam_metalic}
				position={[-12.717, 22.466, -17.673]}
				rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
				scale={[0.125, 0.135, 0.125]}
			/>
			<mesh
				geometry={nodes.Object_10.geometry}
				material={materials.hitam_metalic}
				position={[-12.717, 22.576, -17.673]}
				rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
				scale={[0.125, 0.135, 0.125]}
			/>
			<mesh
				geometry={nodes.Object_12.geometry}
				material={materials.black}
				position={[-12.717, 22.699, -17.673]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[0.123, 0.133, 0.123]}
			/>
			<mesh
				geometry={nodes.Object_14.geometry}
				material={materials.black}
				position={[-12.717, 22.453, -17.673]}
				rotation={[Math.PI, Math.PI / 2, 0]}
				scale={[0.123, 0.133, 0.123]}
			/>
			<mesh
				geometry={nodes.Object_16.geometry}
				material={materials.base}
				position={[-12.846, 22.566, -17.673]}
				rotation={[Math.PI / 2, 0.752, -Math.PI / 2]}
				scale={[0.011, 0.02, 0.02]}
			/>
			<mesh
				geometry={nodes.Object_18.geometry}
				material={materials.base}
				position={[-12.846, 22.566, -17.673]}
				rotation={[-Math.PI / 2, Math.PI / 2, 0]}
				scale={[0.02, 0.017, 0.02]}
			/>
			<mesh
				geometry={nodes.Object_20.geometry}
				material={materials.base}
				position={[-12.894, 22.52, -17.673]}
				rotation={[Math.PI / 2, 0.744, -Math.PI / 2]}
				scale={0.023}
			/>
			<mesh geometry={nodes.Object_22.geometry} material={materials.black} position={[-12.717, 22.788, -17.673]} scale={0.04} />
			<mesh
				geometry={nodes.Object_27.geometry}
				material={materials.base}
				position={[-12.894, 22.52, -17.673]}
				rotation={[Math.PI / 2, 0.744, -Math.PI / 2]}
				scale={0.023}
			/>
			<mesh geometry={nodes.Object_29.geometry} material={materials.black} position={[-12.717, 22.421, -17.673]} />
			<mesh
				geometry={nodes.Object_31.geometry}
				material={materials.black}
				position={[-13.068, 22.367, -17.664]}
				rotation={[0, 0, -0.794]}
				scale={0.036}
			/>
			<mesh
				geometry={nodes.Object_33.geometry}
				material={materials.black}
				position={[-13.28, 22.158, -17.669]}
				rotation={[0, 0, -0.794]}
				scale={0.048}
			/>
			<mesh geometry={nodes.Object_35.geometry} material={materials.black} position={[-13.318, 21.72, -17.667]} scale={0.034} />
			<mesh geometry={nodes.Object_37.geometry} material={materials.black} position={[-13.318, 21.045, -17.667]} scale={0.034} />
		</group>
	);
}

useGLTF.preload("/models/microphone.glb");

export default Mic;
