/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 redGuitar.glb 
Author: meshplalette66 (https://sketchfab.com/meshplalette66)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-electric-guitar-09557746d4fc40249dc58b1f83b6786d
Title: Red_electric_guitar
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function RedGuitar(props) {
	const { nodes, materials } = useGLTF("/models/redGuitar.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={0.004}>
				<group position={[-44.049, 74.59, 22.966]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={500}>
					<mesh geometry={nodes.BassGuitar01Stand01_MI_PlasticEggshell01Black_0.geometry} material={materials.MI_PlasticEggshell01Black} />
					<mesh geometry={nodes.BassGuitar01Stand01_MI_PlasticMatte01Black_0.geometry} material={materials.MI_PlasticMatte01Black} />
				</group>
				<group position={[-47.061, 217.083, 22.903]} rotation={[-Math.PI / 2, 0.244, -Math.PI ]} scale={500}>
					<mesh geometry={nodes.BassGuitar01_MI_BassGuitar01_0.geometry} material={materials.MI_BassGuitar01} />
					<mesh geometry={nodes.BassGuitar01_MI_MetalChromeClean01Thread_0.geometry} material={materials.MI_MetalChromeClean01Thread} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/redGuitar.glb");

export default RedGuitar;
