/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cd.glb 
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cd-music-03-0a7696bb33134cacb5a39eeb0420a738
Title: CD Music 03
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Cd(props) {
	const { nodes, materials } = useGLTF("/models/cd.glb");
	return (
		<group {...props} dispose={null} scale={5}>
			<group position={[0.06, 0.062, 0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_19.geometry} material={materials["cover_back.002"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_21.geometry}
					material={materials["cover_front.002"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_23.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_25.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_27.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[0.14, 0.062, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_30.geometry} material={materials["cover_back.003"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_32.geometry}
					material={materials["cover_front.003"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_34.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_36.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_38.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[0.22, 0.062, 0.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_41.geometry} material={materials["cover_back.004"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_43.geometry}
					material={materials["cover_front.004"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_45.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_47.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_49.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[0.3, 0.062, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_52.geometry} material={materials["cover_back.005"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_54.geometry}
					material={materials["cover_front.005"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_56.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_58.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_60.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[0.38, 0.062, 0.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_63.geometry} material={materials["cover_back.006"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_65.geometry}
					material={materials["cover_front.006"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_67.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_69.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_71.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[-0.34, 0.062, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_74.geometry} material={materials["cover_back.007"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_76.geometry}
					material={materials["cover_front.007"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_78.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_80.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_82.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[-0.26, 0.062, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_85.geometry} material={materials["cover_back.008"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_87.geometry}
					material={materials["cover_front.008"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_89.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_91.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_93.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[-0.18, 0.062, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_96.geometry} material={materials["cover_back.009"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_98.geometry}
					material={materials["cover_front.009"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_100.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_102.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_104.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[-0.1, 0.062, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_107.geometry} material={materials["cover_back.010"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_109.geometry}
					material={materials["cover_front.010"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_111.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_113.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_115.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
			<group position={[-0.02, 0.062, 0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
				<mesh geometry={nodes.Object_118.geometry} material={materials["cover_back.011"]} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_120.geometry}
					material={materials["cover_front.011"]}
					position={[4.449, 6.913, -1.006]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
				<mesh geometry={nodes.Object_122.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
				<mesh geometry={nodes.Object_124.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
				<mesh
					geometry={nodes.Object_126.geometry}
					material={materials.Plastic_transparent}
					position={[18.96, 4.347, -0.332]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={1000}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/cd.glb");
export default Cd;
