/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 couch.glb 
Author: oisougabo (https://sketchfab.com/oisougabo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-couch-443d9bb95e944afe8ebc4ff489e2886c
Title: Old Couch
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Couch(props) {
	const { nodes, materials } = useGLTF("/models/couch.glb");
	return (
		<group {...props} dispose={null} scale={0.015}>
			<mesh geometry={nodes.couch02_lo_lambert1_0.geometry} material={materials.lambert1} />
		</group>
	);
}

useGLTF.preload("/models/couch.glb");

export default Couch;
