/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 drums.glb 
Author: xxcoobloyxx (https://sketchfab.com/xxcoobloyxx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stu-punk-with-drums-with-animations-3d2f2fb28c594855b34eabd6747c8b8f
Title: Stu Punk With Drums With Animations
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function Drums(props) {
	const group = React.useRef();
	const { scene, animations } = useGLTF("/models/drums.glb");
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone);
	const { actions } = useAnimations(animations, group);
	useEffect(() => {
		actions["Animation"].play();
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null} scale={0.25}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
					<group name="root">
						<group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 5.5, 0]}>
							<group name="DRUMKIT_31">
								<group name="GLTF_created_0">
									<primitive object={nodes.GLTF_created_0_rootJoint} />
									<group name="drum_03001_23" />
									<group name="drum_stick_01001_24" />
									<group name="drum_stick_02001_25" />
									<group name="GEO|cymbal_01001_27" />
									<group name="GEO|cymbal_02001_28" />
									<group name="GEO|drum_01001_29" />
									<group name="GEO|drum_02001_30" />
									<skinnedMesh
										name="Object_7"
										geometry={nodes.Object_7.geometry}
										material={materials["Material_1.002"]}
										skeleton={nodes.Object_7.skeleton}
									/>
									<skinnedMesh
										name="Object_8"
										geometry={nodes.Object_8.geometry}
										material={materials["Material_0.002"]}
										skeleton={nodes.Object_8.skeleton}
									/>
									<skinnedMesh
										name="Object_10"
										geometry={nodes.Object_10.geometry}
										material={materials["Material_0.002"]}
										skeleton={nodes.Object_10.skeleton}
									/>
									<skinnedMesh
										name="Object_12"
										geometry={nodes.Object_12.geometry}
										material={materials["Material_0.002"]}
										skeleton={nodes.Object_12.skeleton}
									/>
									<skinnedMesh
										name="Object_14"
										geometry={nodes.Object_14.geometry}
										material={materials["Material_1.002"]}
										skeleton={nodes.Object_14.skeleton}
									/>
									<skinnedMesh
										name="Object_16"
										geometry={nodes.Object_16.geometry}
										material={materials["Material_1.002"]}
										skeleton={nodes.Object_16.skeleton}
									/>
									<skinnedMesh
										name="Object_18"
										geometry={nodes.Object_18.geometry}
										material={materials["Material_1.002"]}
										skeleton={nodes.Object_18.skeleton}
									/>
									<skinnedMesh
										name="Object_19"
										geometry={nodes.Object_19.geometry}
										material={materials["Material_0.002"]}
										skeleton={nodes.Object_19.skeleton}
									/>
									<skinnedMesh
										name="Object_21"
										geometry={nodes.Object_21.geometry}
										material={materials["Material_1.002"]}
										skeleton={nodes.Object_21.skeleton}
									/>
									<skinnedMesh
										name="Object_22"
										geometry={nodes.Object_22.geometry}
										material={materials["Material_0.002"]}
										skeleton={nodes.Object_22.skeleton}
									/>
								</group>
							</group>
							<group name="CHARACTER_150">
								<group name="GLTF_created_1">
									<primitive object={nodes.GLTF_created_1_rootJoint} />
									<group name="body_GEOPIV_135" />
									<group name="cape_GEOPIV_136" />
									<group name="finger_GEOPIV_137" />
									<group name="hands_GEOPIV_146" />
									<group name="head_GEOPIV_147" />
									<group name="helmet_GEOPIV_148" />
									<group name="jacket_GEOPIV_149" />
									<skinnedMesh
										name="Object_50"
										geometry={nodes.Object_50.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_50.skeleton}
									/>
									<skinnedMesh
										name="Object_51"
										geometry={nodes.Object_51.geometry}
										material={materials["Material_1.003"]}
										skeleton={nodes.Object_51.skeleton}
									/>
									<skinnedMesh
										name="Object_53"
										geometry={nodes.Object_53.geometry}
										material={materials["Material_1.003"]}
										skeleton={nodes.Object_53.skeleton}
									/>
									<skinnedMesh
										name="Object_54"
										geometry={nodes.Object_54.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_54.skeleton}
									/>
									<skinnedMesh
										name="Object_56"
										geometry={nodes.Object_56.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_56.skeleton}
									/>
									<skinnedMesh
										name="Object_58"
										geometry={nodes.Object_58.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_58.skeleton}
									/>
									<skinnedMesh
										name="Object_60"
										geometry={nodes.Object_60.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_60.skeleton}
									/>
									<skinnedMesh
										name="Object_62"
										geometry={nodes.Object_62.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_62.skeleton}
									/>
									<skinnedMesh
										name="Object_63"
										geometry={nodes.Object_63.geometry}
										material={materials["Material_1.003"]}
										skeleton={nodes.Object_63.skeleton}
									/>
									<skinnedMesh
										name="Object_65"
										geometry={nodes.Object_65.geometry}
										material={materials["Material_0.003"]}
										skeleton={nodes.Object_65.skeleton}
									/>
									<skinnedMesh
										name="Object_66"
										geometry={nodes.Object_66.geometry}
										material={materials["Material_1.003"]}
										skeleton={nodes.Object_66.skeleton}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/drums.glb");

export default Drums;
