/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitar.glb 
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-musical-trem-playing-guitar-loop-7dde986b68834de6b5a9deff6819d3f1
Title: Animated Musical Trem Playing Guitar Loop
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

 function Guitar(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/guitar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  // console.log(actions);
  useEffect(() => {
    actions['Animation']?.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.611}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="guitar_72" position={[0.381, 0.682, -0.113]} rotation={[-0.457, -0.605, -1.657]} scale={2.156}>
                <group name="root_68">
                  <group name="node_id30_73" position={[0, -0.256, 0.256]} scale={0.109}>
                    <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material} />
                  </group>
                </group>
              </group>
              <group name="Guitar_Playing_(1)_70">
                <group name="Guitar_Playing_(1)_Skeleton_69">
                  <group name="91e81ab3-0a89-48c2-b8ce-a23f28bdf736_Skeleton_0">
                    <group name="GLTF_created_0">
                      <primitive object={nodes.GLTF_created_0_rootJoint} />
                      <group name="Wolf3D_Avatar_71" />
                      <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Wolf3D_Avatar} skeleton={nodes.Object_9.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/guitar.glb')

export default Guitar;