/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitarDeco.glb 
Author: Andrewlxlxl99 (https://sketchfab.com/Andrewlxlxl99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/before-concert-0b02a83f045c42eb809f7aa23b81f65a
Title: Before concert
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function GuitarDeco(props) {
	const { nodes, materials } = useGLTF("/models/guitarDeco.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={0.02}>
				<mesh
					geometry={nodes.CombUp001_Comb_0.geometry}
					material={materials.Comb}
					position={[-12.429, 152.984, 1.087]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Bass001_Bass_0.geometry}
					material={materials.Bass}
					position={[-95.117, 62.791, -43.537]}
					rotation={[-1.678, 0.019, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.CombDown001_Comb_0.geometry}
					material={materials.Comb}
					position={[-11.684, 70.306, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/guitarDeco.glb");

export default GuitarDeco;