/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitarPoster.glb 
Author: POSTOBOY (https://sketchfab.com/johnthyque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hip-poster-prince-256d067e442a4e639fa3b5dce41fa146
Title: Hip Poster PRINCE
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function GuitarPoster(props) {
	const { nodes, materials } = useGLTF("/models/guitarPoster.glb");
	return (
		<group {...props} dispose={null} scale={2}>
			<mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
			<mesh geometry={nodes.Object_6.geometry} material={materials["Material.001"]} position={[0.65, 0, 0]} />
			<mesh geometry={nodes.Object_8.geometry} material={materials["Material.002"]} />
			<mesh geometry={nodes.Object_10.geometry} material={materials["Material.003"]} position={[-0.67, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
			<mesh geometry={nodes.Object_12.geometry} material={materials["Material.004"]} position={[-0.67, 0, 0]} />
			<mesh geometry={nodes.Object_14.geometry} material={materials["Material.005"]} position={[0.65, 0, 0]} />
		</group>
	);
}

useGLTF.preload("/models/guitarPoster.glb");

export default GuitarPoster;
