/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headphone.glb 
Author: Halil Kantarci (https://sketchfab.com/halilkantarci)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphone-with-stand-4ffedc9bffad4a549f6e0a46b0f92b05
Title: Headphone with stand
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function HeadPhone(props) {
  const { nodes, materials } = useGLTF('/models/headphone.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-52.817, 82.966, -29.903]}>
            <mesh geometry={nodes.stand_stand_0.geometry} material={materials.stand} position={[52.836, 62.482, 29.845]} />
            <mesh geometry={nodes['cables__cables+_0'].geometry} material={materials.cables} position={[26.04, 42.44, -11.357]} />
            <mesh geometry={nodes.header_header_0.geometry} material={materials.header} position={[52.817, 194.221, 29.403]} />
            <mesh geometry={nodes.driverL_driverL_0.geometry} material={materials.driverL} position={[12.239, 84.436, 29.903]} />
            <mesh geometry={nodes.driverR_driverR_0.geometry} material={materials.driverR} position={[93.394, 88.311, 29.903]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/headphone.glb')
export default HeadPhone;
