/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
function MusicRoom(props) {
	const { nodes, materials } = useGLTF("/models/optimized-room.glb");
	return (
		<group {...props} dispose={null}>

			<mesh geometry={nodes.body1_blinn1_0.geometry} material={materials.blinn1} />
			<mesh geometry={nodes.window_blinn1_0.geometry} material={materials.blinn1} />
			<mesh geometry={nodes.window4_phong1_0.geometry} material={materials.phong1} />
		</group>
	);
}

useGLTF.preload("/models/optimized-room.glb");

export default MusicRoom;
