/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 piano_animation.glb 
Author: meaghansearle (https://sketchfab.com/meaghansearle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/piano-animation-acafbc9831894ab0a291f1c6e05584b2
Title: Piano Animation
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

function Piano(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/piano_animation.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(() => {
    actions['Take 001']?.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null} scale={0.8}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="0d03c4211813481ea887a1f41ce0445cfbx" rotation={[Math.PI / 2, 3.15, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="pCube64" position={[0, 1.444, -0.565]}>
                    <group name="polySurface1" position={[0, -1.444, 0.565]}>
                      <group name="transform234" />
                    </group>
                    <group name="polySurface2" position={[0, -1.444, 0.565]}>
                      <group name="transform233" />
                    </group>
                    <group name="polySurface3" position={[0, -1.444, 0.565]}>
                      <group name="transform232" />
                    </group>
                    <group name="polySurface4" position={[0, -1.444, 0.565]}>
                      <group name="transform231" />
                    </group>
                    <group name="polySurface5" position={[0, -1.444, 0.565]}>
                      <group name="transform230" />
                    </group>
                    <group name="polySurface6" position={[0, -1.444, 0.565]}>
                      <group name="transform229" />
                    </group>
                    <group name="polySurface7" position={[0, -1.444, 0.565]}>
                      <group name="transform228" />
                    </group>
                    <group name="polySurface8" position={[0, -1.444, 0.565]}>
                      <group name="transform227" />
                    </group>
                    <group name="polySurface9" position={[0, -1.444, 0.565]}>
                      <group name="transform226" />
                    </group>
                    <group name="polySurface10" position={[0, -1.444, 0.565]}>
                      <group name="transform225" />
                    </group>
                    <group name="polySurface11" position={[0, -1.444, 0.565]}>
                      <group name="transform224" />
                    </group>
                    <group name="polySurface12" position={[0, -1.444, 0.565]}>
                      <group name="transform223" />
                    </group>
                    <group name="polySurface13" position={[0, -1.444, 0.565]}>
                      <group name="transform222" />
                    </group>
                    <group name="polySurface14" position={[0, -1.444, 0.565]}>
                      <group name="transform221" />
                    </group>
                    <group name="polySurface15" position={[0, -1.444, 0.565]}>
                      <group name="transform220" />
                    </group>
                    <group name="polySurface16" position={[0, -1.444, 0.565]}>
                      <group name="transform219" />
                    </group>
                    <group name="polySurface17" position={[0, -1.444, 0.565]}>
                      <group name="transform218" />
                    </group>
                    <group name="polySurface18" position={[0, -1.444, 0.565]}>
                      <group name="transform217" />
                    </group>
                    <group name="polySurface19" position={[0, -1.444, 0.565]}>
                      <group name="transform216" />
                    </group>
                    <group name="polySurface20" position={[0, -1.444, 0.565]}>
                      <group name="transform215" />
                    </group>
                    <group name="polySurface21" position={[0, -1.444, 0.565]}>
                      <group name="transform214" />
                    </group>
                    <group name="polySurface22" position={[0, -1.444, 0.565]}>
                      <group name="transform213" />
                    </group>
                    <group name="polySurface23" position={[0, -1.444, 0.565]}>
                      <group name="transform212" />
                    </group>
                    <group name="polySurface24" position={[0, -1.444, 0.565]}>
                      <group name="transform211" />
                    </group>
                    <group name="polySurface25" position={[0, -1.444, 0.565]}>
                      <group name="transform210" />
                    </group>
                    <group name="polySurface26" position={[0, -1.444, 0.565]}>
                      <group name="transform209" />
                    </group>
                    <group name="polySurface27" position={[0, -1.444, 0.565]}>
                      <group name="transform208" />
                    </group>
                    <group name="polySurface28" position={[0, -1.444, 0.565]}>
                      <group name="transform207" />
                    </group>
                    <group name="polySurface29" position={[0, -1.444, 0.565]}>
                      <group name="transform206" />
                    </group>
                    <group name="polySurface30" position={[0, -1.444, 0.565]}>
                      <group name="transform205" />
                    </group>
                    <group name="polySurface31" position={[0, -1.444, 0.565]}>
                      <group name="transform204" />
                    </group>
                    <group name="polySurface32" position={[0, -1.444, 0.565]}>
                      <group name="transform203" />
                    </group>
                    <group name="polySurface33" position={[0, -1.444, 0.565]}>
                      <group name="transform202" />
                    </group>
                    <group name="polySurface34" position={[0, -1.444, 0.565]}>
                      <group name="transform201" />
                    </group>
                    <group name="polySurface35" position={[0, -1.444, 0.565]}>
                      <group name="transform200" />
                    </group>
                    <group name="polySurface37" position={[0, -1.444, 0.565]}>
                      <group name="transform199" />
                    </group>
                    <group name="polySurface38" position={[0, -1.444, 0.565]}>
                      <group name="transform198" />
                    </group>
                    <group name="polySurface39" position={[0, -1.444, 0.565]}>
                      <group name="transform197" />
                    </group>
                    <group name="polySurface41" position={[0, -1.444, 0.565]}>
                      <group name="transform196" />
                    </group>
                    <group name="polySurface42" position={[0, -1.444, 0.565]}>
                      <group name="transform195" />
                    </group>
                    <group name="polySurface43" position={[0, -1.444, 0.565]}>
                      <group name="transform194" />
                    </group>
                    <group name="polySurface44" position={[0, -1.444, 0.565]}>
                      <group name="transform193" />
                    </group>
                    <group name="polySurface45" position={[0, -1.444, 0.565]}>
                      <group name="transform192" />
                    </group>
                    <group name="polySurface46" position={[0, -1.444, 0.565]}>
                      <group name="transform191" />
                    </group>
                    <group name="polySurface47" position={[0, -1.444, 0.565]}>
                      <group name="transform190" />
                    </group>
                    <group name="polySurface48" position={[0, -1.444, 0.565]}>
                      <group name="transform189" />
                    </group>
                    <group name="polySurface49" position={[0, -1.444, 0.565]}>
                      <group name="transform188" />
                    </group>
                    <group name="polySurface50" position={[0, -1.444, 0.565]}>
                      <group name="transform187" />
                    </group>
                    <group name="polySurface51" position={[0, -1.444, 0.565]}>
                      <group name="transform186" />
                    </group>
                    <group name="polySurface52" position={[0, -1.444, 0.565]}>
                      <group name="transform185" />
                    </group>
                    <group name="polySurface53" position={[0, -1.444, 0.565]}>
                      <group name="transform184" />
                    </group>
                    <group name="polySurface54" position={[0, -1.444, 0.565]}>
                      <group name="transform183" />
                    </group>
                    <group name="polySurface55" position={[0, -1.444, 0.565]}>
                      <group name="transform182" />
                    </group>
                    <group name="polySurface56" position={[0, -1.444, 0.565]}>
                      <group name="transform181" />
                    </group>
                    <group name="polySurface57" position={[0, -1.444, 0.565]}>
                      <group name="transform180" />
                    </group>
                    <group name="polySurface58" position={[0, -1.444, 0.565]}>
                      <group name="transform179" />
                    </group>
                    <group name="polySurface59" position={[0, -1.444, 0.565]}>
                      <group name="transform178" />
                    </group>
                    <group name="polySurface60" position={[0, -1.444, 0.565]}>
                      <group name="transform177" />
                    </group>
                    <group name="polySurface61" position={[0, -1.444, 0.565]}>
                      <group name="transform176" />
                    </group>
                    <group name="polySurface62" position={[0, -1.444, 0.565]}>
                      <group name="transform175" />
                    </group>
                    <group name="polySurface63" position={[0, -1.444, 0.565]}>
                      <group name="transform174" />
                    </group>
                    <group name="polySurface64" position={[0, -1.444, 0.565]}>
                      <group name="transform173" />
                    </group>
                    <group name="polySurface65" position={[0, -1.444, 0.565]}>
                      <group name="transform172" />
                    </group>
                    <group name="polySurface66" position={[0, -1.444, 0.565]}>
                      <group name="transform171" />
                    </group>
                    <group name="polySurface67" position={[0, -1.444, 0.565]}>
                      <group name="transform170" />
                    </group>
                    <group name="polySurface68" position={[0, -1.444, 0.565]}>
                      <group name="transform169" />
                    </group>
                    <group name="polySurface69" position={[0, -1.444, 0.565]}>
                      <group name="transform168" />
                    </group>
                    <group name="polySurface70" position={[0, -1.444, 0.565]}>
                      <group name="transform167" />
                    </group>
                    <group name="polySurface71" position={[0, -1.444, 0.565]}>
                      <group name="transform166" />
                    </group>
                    <group name="polySurface72" position={[0, -1.444, 0.565]}>
                      <group name="transform165" />
                    </group>
                    <group name="polySurface73" position={[0, -1.444, 0.565]}>
                      <group name="transform164" />
                    </group>
                    <group name="polySurface74" position={[0, -1.444, 0.565]}>
                      <group name="transform163" />
                    </group>
                    <group name="polySurface75" position={[0, -1.444, 0.565]}>
                      <group name="transform162" />
                    </group>
                    <group name="polySurface76" position={[0, -1.444, 0.565]}>
                      <group name="transform161" />
                    </group>
                    <group name="polySurface77" position={[0, -1.444, 0.565]}>
                      <group name="transform160" />
                    </group>
                    <group name="polySurface78" position={[0, -1.444, 0.565]}>
                      <group name="transform159" />
                    </group>
                    <group name="polySurface79" position={[0, -1.444, 0.565]}>
                      <group name="transform158" />
                    </group>
                    <group name="polySurface80" position={[0, -1.444, 0.565]}>
                      <group name="transform157" />
                    </group>
                    <group name="polySurface81" position={[0, -1.444, 0.565]}>
                      <group name="transform156" />
                    </group>
                    <group name="polySurface82" position={[0, -1.444, 0.565]}>
                      <group name="transform155" />
                    </group>
                    <group name="polySurface83" position={[0, -1.444, 0.565]}>
                      <group name="transform154" />
                    </group>
                    <group name="polySurface84" position={[0, -1.444, 0.565]}>
                      <group name="transform153" />
                    </group>
                    <group name="polySurface85" position={[0, -1.444, 0.565]}>
                      <group name="transform152" />
                    </group>
                    <group name="polySurface86" position={[0, -1.444, 0.565]}>
                      <group name="transform151" />
                    </group>
                    <group name="polySurface87" position={[0, -1.444, 0.565]}>
                      <group name="transform150" />
                    </group>
                    <group name="polySurface88" position={[0, -1.444, 0.565]}>
                      <group name="transform149" />
                    </group>
                    <group name="polySurface89" position={[0, -1.444, 0.565]}>
                      <group name="transform148" />
                    </group>
                    <group name="polySurface90" position={[0, -1.444, 0.565]}>
                      <group name="transform147" />
                    </group>
                    <group name="polySurface91" position={[0, -1.444, 0.565]}>
                      <group name="transform146" />
                    </group>
                    <group name="polySurface92" position={[0, -1.444, 0.565]}>
                      <group name="transform145" />
                    </group>
                    <group name="polySurface93" position={[0, -1.444, 0.565]}>
                      <group name="transform144" />
                    </group>
                    <group name="polySurface94" position={[0, -1.444, 0.565]}>
                      <group name="transform143" />
                    </group>
                    <group name="polySurface95" position={[0, -1.444, 0.565]}>
                      <group name="transform142" />
                    </group>
                    <group name="polySurface96" position={[0, -1.444, 0.565]}>
                      <group name="transform141" />
                    </group>
                    <group name="polySurface97" position={[0, -1.444, 0.565]}>
                      <group name="transform140" />
                    </group>
                    <group name="polySurface98" position={[0, -1.444, 0.565]}>
                      <group name="transform139" />
                    </group>
                    <group name="polySurface99" position={[0, -1.444, 0.565]}>
                      <group name="transform138" />
                    </group>
                    <group name="polySurface100" position={[0, -1.444, 0.565]}>
                      <group name="transform137" />
                    </group>
                    <group name="polySurface101" position={[0, -1.444, 0.565]}>
                      <group name="transform136" />
                    </group>
                    <group name="polySurface102" position={[0, -1.444, 0.565]}>
                      <group name="transform135" />
                    </group>
                    <group name="polySurface103" position={[0, -1.444, 0.565]}>
                      <group name="transform134" />
                    </group>
                    <group name="polySurface104" position={[0, -1.444, 0.565]}>
                      <group name="transform133" />
                    </group>
                    <group name="polySurface105" position={[0, -1.444, 0.565]}>
                      <group name="transform132" />
                    </group>
                    <group name="polySurface106" position={[0, -1.444, 0.565]}>
                      <group name="transform131" />
                    </group>
                    <group name="polySurface107" position={[0, -1.444, 0.565]}>
                      <group name="transform130" />
                    </group>
                    <group name="polySurface108" position={[0, -1.444, 0.565]}>
                      <group name="transform129" />
                    </group>
                    <group name="polySurface109" position={[0, -1.444, 0.565]}>
                      <group name="transform128" />
                    </group>
                    <group name="polySurface110" position={[0, -1.444, 0.565]}>
                      <group name="transform127" />
                    </group>
                    <group name="polySurface111" position={[0, -1.444, 0.565]}>
                      <group name="transform126" />
                    </group>
                    <group name="polySurface112" position={[0, -1.444, 0.565]}>
                      <group name="transform125" />
                    </group>
                    <group name="polySurface113" position={[0, -1.444, 0.565]}>
                      <group name="transform124" />
                    </group>
                    <group name="polySurface114" position={[0, -1.444, 0.565]}>
                      <group name="transform123" />
                    </group>
                    <group name="polySurface115" position={[0, -1.444, 0.565]}>
                      <group name="transform122" />
                    </group>
                    <group name="polySurface116" position={[0, -1.444, 0.565]}>
                      <group name="transform121" />
                    </group>
                    <group name="polySurface117" position={[0, -1.444, 0.565]}>
                      <group name="transform120" />
                    </group>
                    <group name="polySurface118" position={[0, -1.444, 0.565]}>
                      <group name="transform119" />
                    </group>
                    <group name="polySurface119" position={[0, -1.444, 0.565]}>
                      <group name="transform118" />
                    </group>
                    <group name="polySurface120" position={[0, -1.444, 0.565]}>
                      <group name="transform117" />
                    </group>
                    <group name="polySurface121" position={[0, -1.444, 0.565]}>
                      <group name="transform116" />
                    </group>
                    <group name="polySurface122" position={[0, -1.444, 0.565]}>
                      <group name="transform115" />
                    </group>
                    <group name="polySurface123" position={[0, -1.444, 0.565]}>
                      <group name="transform114" />
                    </group>
                    <group name="polySurface124" position={[0, -1.444, 0.565]}>
                      <group name="transform113" />
                    </group>
                    <group name="polySurface125" position={[0, -1.444, 0.565]}>
                      <group name="transform112" />
                    </group>
                    <group name="polySurface126" position={[0, -1.444, 0.565]}>
                      <group name="transform111" />
                    </group>
                    <group name="polySurface127" position={[0, -1.444, 0.565]}>
                      <group name="transform110" />
                    </group>
                    <group name="polySurface128" position={[0, -1.444, 0.565]}>
                      <group name="transform109" />
                    </group>
                    <group name="polySurface129" position={[0, -1.444, 0.565]}>
                      <group name="transform108" />
                    </group>
                    <group name="polySurface130" position={[0, -1.444, 0.565]}>
                      <group name="transform107" />
                    </group>
                    <group name="polySurface131" position={[0, -1.444, 0.565]}>
                      <group name="transform106" />
                    </group>
                    <group name="polySurface132" position={[0, -1.444, 0.565]}>
                      <group name="transform105" />
                    </group>
                    <group name="polySurface133" position={[0, -1.444, 0.565]}>
                      <group name="transform104" />
                    </group>
                    <group name="polySurface134" position={[0, -1.444, 0.565]}>
                      <group name="transform103" />
                    </group>
                    <group name="polySurface135" position={[0, -1.444, 0.565]}>
                      <group name="transform102" />
                    </group>
                    <group name="polySurface136" position={[0, -1.444, 0.565]}>
                      <group name="transform101" />
                    </group>
                    <group name="polySurface137" position={[0, -1.444, 0.565]}>
                      <group name="transform100" />
                    </group>
                    <group name="polySurface138" position={[0, -1.444, 0.565]}>
                      <group name="transform99" />
                    </group>
                    <group name="polySurface139" position={[0, -1.444, 0.565]}>
                      <group name="transform98" />
                    </group>
                    <group name="polySurface140" position={[0, -1.444, 0.565]}>
                      <group name="transform97" />
                    </group>
                    <group name="polySurface141" position={[0, -1.444, 0.565]}>
                      <group name="transform96" />
                    </group>
                    <group name="polySurface142" position={[0, -1.444, 0.565]}>
                      <group name="transform95" />
                    </group>
                    <group name="polySurface143" position={[0, -1.444, 0.565]}>
                      <group name="transform94" />
                    </group>
                    <group name="polySurface144" position={[0, -1.444, 0.565]}>
                      <group name="transform93" />
                    </group>
                    <group name="polySurface145" position={[0, -1.444, 0.565]}>
                      <group name="transform92" />
                    </group>
                    <group name="polySurface146" position={[0, -1.444, 0.565]}>
                      <group name="transform91" />
                    </group>
                    <group name="polySurface147" position={[0, -1.444, 0.565]}>
                      <group name="transform90" />
                    </group>
                    <group name="polySurface148" position={[0, -1.444, 0.565]}>
                      <group name="transform89" />
                    </group>
                    <group name="polySurface149" position={[0, -1.444, 0.565]}>
                      <group name="transform88" />
                    </group>
                    <group name="polySurface150" position={[0, -1.444, 0.565]}>
                      <group name="transform87" />
                    </group>
                    <group name="polySurface151" position={[0, -1.444, 0.565]}>
                      <group name="transform86" />
                    </group>
                    <group name="polySurface152" position={[0, -1.444, 0.565]}>
                      <group name="transform85" />
                    </group>
                    <group name="polySurface153" position={[0, -1.444, 0.565]}>
                      <group name="transform84" />
                    </group>
                    <group name="polySurface154" position={[0, -1.444, 0.565]}>
                      <group name="transform83" />
                    </group>
                    <group name="polySurface155" position={[0, -1.444, 0.565]}>
                      <group name="transform82" />
                    </group>
                    <group name="polySurface156" position={[0, -1.444, 0.565]}>
                      <group name="transform81" />
                    </group>
                    <group name="polySurface157" position={[0, -1.444, 0.565]}>
                      <group name="transform80" />
                    </group>
                    <group name="polySurface158" position={[0, -1.444, 0.565]}>
                      <group name="transform79" />
                    </group>
                    <group name="polySurface159" position={[0, -1.444, 0.565]}>
                      <group name="transform78" />
                    </group>
                    <group name="polySurface160" position={[0, -1.444, 0.565]}>
                      <group name="transform77" />
                    </group>
                    <group name="polySurface161" position={[0, -1.444, 0.565]}>
                      <group name="transform76" />
                    </group>
                    <group name="polySurface162" position={[0, -1.444, 0.565]}>
                      <group name="transform75" />
                    </group>
                    <group name="polySurface163" position={[0, -1.444, 0.565]}>
                      <group name="transform74" />
                    </group>
                    <group name="polySurface164" position={[0, -1.444, 0.565]}>
                      <group name="transform73" />
                    </group>
                    <group name="polySurface165" position={[0, -1.444, 0.565]}>
                      <group name="transform72" />
                    </group>
                    <group name="polySurface166" position={[0, -1.444, 0.565]}>
                      <group name="transform71" />
                    </group>
                    <group name="polySurface167" position={[0, -1.444, 0.565]}>
                      <group name="transform70" />
                    </group>
                    <group name="polySurface168" position={[0, -1.444, 0.565]}>
                      <group name="transform69" />
                    </group>
                    <group name="polySurface169" position={[0, -1.444, 0.565]}>
                      <group name="transform68" />
                    </group>
                    <group name="polySurface170" position={[0, -1.444, 0.565]}>
                      <group name="transform67" />
                    </group>
                    <group name="polySurface171" position={[0, -1.444, 0.565]}>
                      <group name="transform66" />
                    </group>
                    <group name="polySurface172" position={[0, -1.444, 0.565]}>
                      <group name="transform65" />
                    </group>
                    <group name="polySurface173" position={[0, -1.444, 0.565]}>
                      <group name="transform64" />
                    </group>
                    <group name="polySurface174" position={[0, -1.444, 0.565]}>
                      <group name="transform63" />
                    </group>
                    <group name="polySurface175" position={[0, -1.444, 0.565]}>
                      <group name="transform62" />
                    </group>
                    <group name="polySurface176" position={[0, -1.444, 0.565]}>
                      <group name="transform61" />
                    </group>
                    <group name="polySurface177" position={[0, -1.444, 0.565]}>
                      <group name="transform60" />
                    </group>
                    <group name="polySurface178" position={[0, -1.444, 0.565]}>
                      <group name="transform59" />
                    </group>
                    <group name="polySurface179" position={[0, -1.444, 0.565]}>
                      <group name="transform58" />
                    </group>
                    <group name="polySurface180" position={[0, -1.444, 0.565]}>
                      <group name="transform57" />
                    </group>
                    <group name="polySurface181" position={[0, -1.444, 0.565]}>
                      <group name="transform56" />
                    </group>
                    <group name="polySurface182" position={[0, -1.444, 0.565]}>
                      <group name="transform55" />
                    </group>
                    <group name="polySurface183" position={[0, -1.444, 0.565]}>
                      <group name="transform54" />
                    </group>
                    <group name="polySurface184" position={[0, -1.444, 0.565]}>
                      <group name="transform53" />
                    </group>
                    <group name="polySurface185" position={[0, -1.444, 0.565]}>
                      <group name="transform52" />
                    </group>
                    <group name="polySurface186" position={[0, -1.444, 0.565]}>
                      <group name="transform51" />
                    </group>
                    <group name="polySurface187" position={[0, -1.444, 0.565]}>
                      <group name="transform50" />
                    </group>
                    <group name="polySurface188" position={[0, -1.444, 0.565]}>
                      <group name="transform49" />
                    </group>
                    <group name="polySurface189" position={[0, -1.444, 0.565]}>
                      <group name="transform48" />
                    </group>
                    <group name="polySurface190" position={[0, -1.444, 0.565]}>
                      <group name="transform47" />
                    </group>
                    <group name="polySurface191" position={[0, -1.444, 0.565]}>
                      <group name="transform46" />
                    </group>
                    <group name="polySurface192" position={[0, -1.444, 0.565]}>
                      <group name="transform45" />
                    </group>
                    <group name="transform1" position={[0, -1.444, 0.565]} />
                    <group name="polySurface193" position={[-2.994, -0.904, -0.618]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform44" />
                    </group>
                    <group name="polySurface194" position={[-2.994, -0.904, -0.487]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform43" />
                    </group>
                    <group name="polySurface195" position={[-2.994, -0.904, -0.349]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform42" />
                    </group>
                    <group name="polySurface196" position={[-2.994, -0.904, -0.212]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform41" />
                    </group>
                    <group name="polySurface197" position={[-2.994, -0.904, -0.077]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform40" />
                    </group>
                    <group name="polySurface198" position={[-2.994, -0.904, 0.063]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform39" />
                    </group>
                    <group name="polySurface199" position={[-2.994, -0.904, 0.198]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform38" />
                    </group>
                    <group name="polySurface200" position={[-2.994, -0.904, 0.332]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform37" />
                    </group>
                    <group name="polySurface201" position={[-2.994, -0.904, 0.457]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform36" />
                    </group>
                    <group name="polySurface202" position={[4.312, -0.904, 0.457]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform7" />
                    </group>
                    <group name="polySurface203" position={[4.312, -0.904, 0.332]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform8" />
                    </group>
                    <group name="polySurface204" position={[4.312, -0.904, 0.198]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform9" />
                    </group>
                    <group name="polySurface205_1" position={[4.312, -0.904, 0.063]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform10" />
                    </group>
                    <group name="polySurface206" position={[4.312, -0.904, -0.077]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform5" />
                    </group>
                    <group name="polySurface207" position={[4.312, -0.904, -0.212]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform6" />
                    </group>
                    <group name="polySurface208" position={[4.312, -0.904, -0.349]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform4" />
                    </group>
                    <group name="polySurface209" position={[4.312, -0.904, -0.487]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform2" />
                    </group>
                    <group name="polySurface210" position={[4.312, -0.904, -0.618]} rotation={[0, 1.57, 0]} scale={0.512}>
                      <group name="transform3" />
                    </group>
                  </group>
                  <group name="pCube65" position={[1.822, 2.73, -0.364]} scale={[0.682, 1.055, 0.043]}>
                    <group name="transform35" />
                  </group>
                  <group name="pCube66" position={[-1.821, 2.73, -0.364]} scale={[0.682, 1.055, 0.043]}>
                    <group name="transform34" />
                  </group>
                  <group name="polySurface205" position={[2.82, 1.852, -0.073]} rotation={[-Math.PI, 0, -Math.PI]}>
                    <group name="transform33" position={[-4.483, -1.852, 0.073]} />
                  </group>
                  <group name="pCube67" position={[-3.575, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform11" />
                  </group>
                  <group name="pCube68" position={[-3.439, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform12" />
                  </group>
                  <group name="pCube69" position={[-3.293, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform13" />
                  </group>
                  <group name="pCube70" position={[-3.143, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform14" />
                  </group>
                  <group name="pCube71" position={[-2.998, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform15" />
                  </group>
                  <group name="pCube72" position={[-2.849, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform16" />
                  </group>
                  <group name="pCube73" position={[-2.696, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform17" />
                  </group>
                  <group name="pCube74" position={[-2.536, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform18" />
                  </group>
                  <group name="pCube75" position={[-2.372, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform19" />
                  </group>
                  <group name="pCube76" position={[-2.216, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform20" />
                  </group>
                  <group name="pCube77" position={[-2.062, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform21" />
                  </group>
                  <group name="pCube78" position={[-1.914, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform22" />
                  </group>
                  <group name="pCube79" position={[-1.774, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform23" />
                  </group>
                  <group name="pCube80" position={[-1.477, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform32" />
                  </group>
                  <group name="pCube81" position={[-1.318, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform31" />
                  </group>
                  <group name="pCube82" position={[-1.155, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform30" />
                  </group>
                  <group name="pCube83" position={[-1.002, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform29" />
                  </group>
                  <group name="pCube84" position={[-0.839, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform28" />
                  </group>
                  <group name="pCube85" position={[-0.666, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform27" />
                  </group>
                  <group name="pCube86" position={[-0.53, 0.202, -0.513]} scale={[0.082, 0.987, 0.069]}>
                    <group name="transform26" />
                  </group>
                  <group name="pCube87" position={[-1.668, 1.233, -1.581]}>
                    <group name="transform25" position={[1.668, -1.233, 1.581]} />
                  </group>
                  <group name="pCube88" position={[1.661, 1.233, -1.581]}>
                    <group name="transform24" position={[1.668, -1.233, 1.581]} />
                  </group>
                  <group name="pCube89" position={[0, 1.444, -0.565]}>
                    <group name="polySurface211" position={[0, -1.444, 0.565]}>
                      <group name="transform478" />
                    </group>
                    <group name="polySurface212" position={[0, -1.444, 0.565]}>
                      <group name="transform477" />
                    </group>
                    <group name="polySurface213" position={[0, -1.444, 0.565]}>
                      <group name="transform476" />
                    </group>
                    <group name="polySurface214" position={[0, -1.444, 0.565]}>
                      <group name="transform475" />
                    </group>
                    <group name="polySurface215" position={[0, -1.444, 0.565]}>
                      <group name="transform474" />
                    </group>
                    <group name="polySurface216" position={[0, -1.444, 0.565]}>
                      <group name="transform473" />
                    </group>
                    <group name="polySurface217" position={[0, -1.444, 0.565]}>
                      <group name="transform472" />
                    </group>
                    <group name="polySurface218" position={[0, -1.444, 0.565]}>
                      <group name="transform471" />
                    </group>
                    <group name="polySurface219" position={[0, -1.444, 0.565]}>
                      <group name="transform470" />
                    </group>
                    <group name="polySurface220" position={[0, -1.444, 0.565]}>
                      <group name="transform469" />
                    </group>
                    <group name="polySurface221" position={[0, -1.444, 0.565]}>
                      <group name="transform468" />
                    </group>
                    <group name="polySurface222" position={[0, -1.444, 0.565]}>
                      <group name="transform467" />
                    </group>
                    <group name="polySurface223" position={[0, -1.444, 0.565]}>
                      <group name="transform466" />
                    </group>
                    <group name="polySurface224" position={[0, -1.444, 0.565]}>
                      <group name="transform465" />
                    </group>
                    <group name="polySurface225" position={[0, -1.444, 0.565]}>
                      <group name="transform464" />
                    </group>
                    <group name="polySurface226" position={[0, -1.444, 0.565]}>
                      <group name="transform463" />
                    </group>
                    <group name="polySurface227" position={[0, -1.444, 0.565]}>
                      <group name="transform462" />
                    </group>
                    <group name="polySurface228" position={[0, -1.444, 0.565]}>
                      <group name="transform461" />
                    </group>
                    <group name="polySurface229" position={[0, -1.444, 0.565]}>
                      <group name="transform460" />
                    </group>
                    <group name="polySurface230" position={[0, -1.444, 0.565]}>
                      <group name="transform459" />
                    </group>
                    <group name="polySurface231" position={[0, -1.444, 0.565]}>
                      <group name="transform458" />
                    </group>
                    <group name="polySurface232" position={[0, -1.444, 0.565]}>
                      <group name="transform457" />
                    </group>
                    <group name="polySurface233" position={[0, -1.444, 0.565]}>
                      <group name="transform456" />
                    </group>
                    <group name="polySurface234" position={[0, -1.444, 0.565]}>
                      <group name="transform455" />
                    </group>
                    <group name="polySurface235" position={[0, -1.444, 0.565]}>
                      <group name="transform454" />
                    </group>
                    <group name="polySurface236" position={[0, -1.444, 0.565]}>
                      <group name="transform453" />
                    </group>
                    <group name="polySurface237" position={[0, -1.444, 0.565]}>
                      <group name="transform452" />
                    </group>
                    <group name="polySurface238" position={[0, -1.444, 0.565]}>
                      <group name="transform451" />
                    </group>
                    <group name="polySurface239" position={[0, -1.444, 0.565]}>
                      <group name="transform450" />
                    </group>
                    <group name="polySurface240" position={[0, -1.444, 0.565]}>
                      <group name="transform449" />
                    </group>
                    <group name="polySurface241" position={[0, -1.444, 0.565]}>
                      <group name="transform448" />
                    </group>
                    <group name="polySurface242" position={[0, -1.444, 0.565]}>
                      <group name="transform447" />
                    </group>
                    <group name="polySurface243" position={[0, -1.444, 0.565]}>
                      <group name="transform446" />
                    </group>
                    <group name="polySurface244" position={[0, -1.444, 0.565]}>
                      <group name="transform445" />
                    </group>
                    <group name="polySurface245" position={[0, -1.444, 0.565]}>
                      <group name="transform444" />
                    </group>
                    <group name="polySurface246" position={[0, -1.444, 0.565]}>
                      <group name="transform443" />
                    </group>
                    <group name="polySurface247" position={[0, -1.444, 0.565]}>
                      <group name="transform442" />
                    </group>
                    <group name="polySurface248" position={[0, -1.444, 0.565]}>
                      <group name="transform441" />
                    </group>
                    <group name="polySurface249" position={[0, -1.444, 0.565]}>
                      <group name="transform440" />
                    </group>
                    <group name="polySurface250" position={[0, -1.444, 0.565]}>
                      <group name="transform439" />
                    </group>
                    <group name="polySurface251" position={[0, -1.444, 0.565]}>
                      <group name="transform438" />
                    </group>
                    <group name="polySurface252" position={[0, -1.444, 0.565]}>
                      <group name="transform437" />
                    </group>
                    <group name="polySurface253" position={[0, -1.444, 0.565]}>
                      <group name="transform436" />
                    </group>
                    <group name="polySurface254" position={[0, -1.444, 0.565]}>
                      <group name="transform435" />
                    </group>
                    <group name="polySurface255" position={[0, -1.444, 0.565]}>
                      <group name="transform434" />
                    </group>
                    <group name="polySurface256" position={[0, -1.444, 0.565]}>
                      <group name="transform433" />
                    </group>
                    <group name="polySurface257" position={[0, -1.444, 0.565]}>
                      <group name="transform432" />
                    </group>
                    <group name="polySurface258" position={[0, -1.444, 0.565]}>
                      <group name="transform431" />
                    </group>
                    <group name="polySurface259" position={[0, -1.444, 0.565]}>
                      <group name="transform430" />
                    </group>
                    <group name="polySurface260" position={[0, -1.444, 0.565]}>
                      <group name="transform429" />
                    </group>
                    <group name="polySurface261" position={[0, -1.444, 0.565]}>
                      <group name="transform428" />
                    </group>
                    <group name="polySurface262" position={[0, -1.444, 0.565]}>
                      <group name="transform427" />
                    </group>
                    <group name="polySurface263" position={[0, -1.444, 0.565]}>
                      <group name="transform426" />
                    </group>
                    <group name="polySurface264" position={[0, -1.444, 0.565]}>
                      <group name="transform425" />
                    </group>
                    <group name="polySurface265" position={[0, -1.444, 0.565]}>
                      <group name="transform424" />
                    </group>
                    <group name="polySurface266" position={[0, -1.444, 0.565]}>
                      <group name="transform423" />
                    </group>
                    <group name="polySurface267" position={[0, -1.444, 0.565]}>
                      <group name="transform422" />
                    </group>
                    <group name="polySurface268" position={[0, -1.444, 0.565]}>
                      <group name="transform421" />
                    </group>
                    <group name="polySurface269" position={[0, -1.444, 0.565]}>
                      <group name="transform420" />
                    </group>
                    <group name="polySurface270" position={[0, -1.444, 0.565]}>
                      <group name="transform419" />
                    </group>
                    <group name="polySurface271" position={[0, -1.444, 0.565]}>
                      <group name="transform418" />
                    </group>
                    <group name="polySurface272" position={[0, -1.444, 0.565]}>
                      <group name="transform417" />
                    </group>
                    <group name="polySurface273" position={[0, -1.444, 0.565]}>
                      <group name="transform416" />
                    </group>
                    <group name="polySurface274" position={[0, -1.444, 0.565]}>
                      <group name="transform415" />
                    </group>
                    <group name="polySurface275" position={[0, -1.444, 0.565]}>
                      <group name="transform414" />
                    </group>
                    <group name="polySurface276" position={[0, -1.444, 0.565]}>
                      <group name="transform413" />
                    </group>
                    <group name="polySurface277" position={[0, -1.444, 0.565]}>
                      <group name="transform412" />
                    </group>
                    <group name="polySurface278" position={[0, -1.444, 0.565]}>
                      <group name="transform411" />
                    </group>
                    <group name="polySurface279" position={[0, -1.444, 0.565]}>
                      <group name="transform410" />
                    </group>
                    <group name="polySurface280" position={[0, -1.444, 0.565]}>
                      <group name="transform409" />
                    </group>
                    <group name="polySurface281" position={[0, -1.425, 0.565]}>
                      <group name="transform408" />
                    </group>
                    <group name="polySurface282" position={[0, -1.425, 0.565]}>
                      <group name="transform407" />
                    </group>
                    <group name="polySurface283" position={[0, -1.425, 0.565]}>
                      <group name="transform406" />
                    </group>
                    <group name="polySurface284" position={[0, -1.425, 0.565]}>
                      <group name="transform405" />
                    </group>
                    <group name="polySurface285" position={[0, -1.425, 0.565]}>
                      <group name="transform404" />
                    </group>
                    <group name="polySurface286" position={[0, -1.425, 0.565]}>
                      <group name="transform403" />
                    </group>
                    <group name="polySurface287" position={[0, -1.425, 0.565]}>
                      <group name="transform402" />
                    </group>
                    <group name="polySurface288" position={[0, -1.425, 0.565]}>
                      <group name="transform401" />
                    </group>
                    <group name="polySurface289" position={[0, -1.425, 0.565]}>
                      <group name="transform400" />
                    </group>
                    <group name="polySurface290" position={[0, -1.425, 0.565]}>
                      <group name="transform399" />
                    </group>
                    <group name="polySurface291" position={[0, -1.425, 0.565]}>
                      <group name="transform398" />
                    </group>
                    <group name="polySurface292" position={[0, -1.425, 0.565]}>
                      <group name="transform397" />
                    </group>
                    <group name="polySurface293" position={[0, -1.425, 0.565]}>
                      <group name="transform396" />
                    </group>
                    <group name="polySurface294" position={[0, -1.425, 0.565]}>
                      <group name="transform395" />
                    </group>
                    <group name="polySurface295" position={[0, -1.425, 0.565]}>
                      <group name="transform394" />
                    </group>
                    <group name="polySurface296" position={[0, -1.425, 0.565]}>
                      <group name="transform393" />
                    </group>
                    <group name="polySurface297" position={[0, -1.425, 0.565]}>
                      <group name="transform392" />
                    </group>
                    <group name="polySurface298" position={[0, -1.425, 0.565]}>
                      <group name="transform391" />
                    </group>
                    <group name="polySurface299" position={[0, -1.444, 0.565]}>
                      <group name="transform390" />
                    </group>
                    <group name="polySurface300" position={[0, -1.444, 0.565]}>
                      <group name="transform389" />
                    </group>
                    <group name="polySurface301" position={[0, -1.444, 0.565]}>
                      <group name="transform388" />
                    </group>
                    <group name="polySurface302" position={[0, -1.444, 0.565]}>
                      <group name="transform387" />
                    </group>
                    <group name="polySurface303" position={[0, -1.444, 0.565]}>
                      <group name="transform386" />
                    </group>
                    <group name="polySurface304" position={[0, -1.444, 0.565]}>
                      <group name="transform385" />
                    </group>
                    <group name="polySurface305" position={[0, -1.444, 0.565]}>
                      <group name="transform384" />
                    </group>
                    <group name="polySurface306" position={[0, -1.444, 0.565]}>
                      <group name="transform383" />
                    </group>
                    <group name="polySurface307" position={[0, -1.444, 0.565]}>
                      <group name="transform382" />
                    </group>
                    <group name="polySurface308" position={[0, -1.444, 0.565]}>
                      <group name="transform381" />
                    </group>
                    <group name="polySurface309" position={[0, -1.444, 0.565]}>
                      <group name="transform380" />
                    </group>
                    <group name="polySurface310" position={[0, -1.444, 0.565]}>
                      <group name="transform379" />
                    </group>
                    <group name="polySurface311" position={[0, -1.444, 0.565]}>
                      <group name="transform378" />
                    </group>
                    <group name="polySurface312" position={[0, -1.444, 0.565]}>
                      <group name="transform377" />
                    </group>
                    <group name="polySurface313" position={[0, -1.444, 0.565]}>
                      <group name="transform376" />
                    </group>
                    <group name="polySurface314" position={[0, -1.444, 0.565]}>
                      <group name="transform375" />
                    </group>
                    <group name="polySurface315" position={[0, -1.444, 0.565]}>
                      <group name="transform374" />
                    </group>
                    <group name="polySurface316" position={[0, -1.444, 0.565]}>
                      <group name="transform373" />
                    </group>
                    <group name="polySurface317" position={[0, -1.444, 0.565]}>
                      <group name="transform372" />
                    </group>
                    <group name="polySurface318" position={[0, -1.444, 0.565]}>
                      <group name="transform371" />
                    </group>
                    <group name="polySurface319" position={[0, -1.444, 0.565]}>
                      <group name="transform370" />
                    </group>
                    <group name="polySurface320" position={[0, -1.444, 0.565]}>
                      <group name="transform369" />
                    </group>
                    <group name="polySurface321" position={[0, -1.444, 0.565]}>
                      <group name="transform368" />
                    </group>
                    <group name="polySurface322" position={[0, -1.444, 0.565]}>
                      <group name="transform367" />
                    </group>
                    <group name="polySurface323" position={[0, -1.444, 0.565]}>
                      <group name="transform366" />
                    </group>
                    <group name="polySurface324" position={[0, -1.444, 0.565]}>
                      <group name="transform365" />
                    </group>
                    <group name="polySurface325" position={[0, -1.444, 0.565]}>
                      <group name="transform364" />
                    </group>
                    <group name="polySurface326" position={[0, -1.444, 0.565]}>
                      <group name="transform363" />
                    </group>
                    <group name="polySurface327" position={[0, -1.444, 0.565]}>
                      <group name="transform362" />
                    </group>
                    <group name="polySurface328" position={[0, -1.444, 0.565]}>
                      <group name="transform361" />
                    </group>
                    <group name="polySurface329" position={[0, -1.444, 0.565]}>
                      <group name="transform360" />
                    </group>
                    <group name="polySurface330" position={[0, -1.444, 0.565]}>
                      <group name="transform359" />
                    </group>
                    <group name="polySurface331" position={[0, -1.444, 0.565]}>
                      <group name="transform358" />
                    </group>
                    <group name="polySurface332" position={[0, -1.444, 0.565]}>
                      <group name="transform357" />
                    </group>
                    <group name="polySurface333" position={[0, -1.444, 0.565]}>
                      <group name="transform356" />
                    </group>
                    <group name="polySurface334" position={[0, -1.444, 0.565]}>
                      <group name="transform355" />
                    </group>
                    <group name="polySurface335" position={[0, -1.444, 0.565]}>
                      <group name="transform354" />
                    </group>
                    <group name="polySurface336" position={[0, -1.444, 0.565]}>
                      <group name="transform353" />
                    </group>
                    <group name="polySurface337" position={[0, -1.444, 0.565]}>
                      <group name="transform352" />
                    </group>
                    <group name="polySurface338" position={[0, -1.444, 0.565]}>
                      <group name="transform351" />
                    </group>
                    <group name="polySurface339" position={[0, -1.444, 0.565]}>
                      <group name="transform350" />
                    </group>
                    <group name="polySurface340" position={[0, -1.444, 0.565]}>
                      <group name="transform349" />
                    </group>
                    <group name="polySurface341" position={[0, -1.444, 0.565]}>
                      <group name="transform348" />
                    </group>
                    <group name="polySurface342" position={[0, -1.444, 0.565]}>
                      <group name="transform347" />
                    </group>
                    <group name="polySurface343" position={[0, -1.444, 0.565]}>
                      <group name="transform346" />
                    </group>
                    <group name="polySurface344" position={[0, -1.444, 0.565]}>
                      <group name="transform345" />
                    </group>
                    <group name="polySurface345" position={[0, -1.444, 0.565]}>
                      <group name="transform344" />
                    </group>
                    <group name="polySurface346" position={[0, -1.444, 0.565]}>
                      <group name="transform343" />
                    </group>
                    <group name="polySurface347" position={[0, -1.444, 0.565]}>
                      <group name="transform342" />
                    </group>
                    <group name="polySurface348" position={[0, -1.444, 0.565]}>
                      <group name="transform341" />
                    </group>
                    <group name="polySurface349" position={[0, -1.444, 0.565]}>
                      <group name="transform340" />
                    </group>
                    <group name="polySurface350" position={[0, -1.444, 0.565]}>
                      <group name="transform339" />
                    </group>
                    <group name="polySurface351" position={[0, -1.444, 0.565]}>
                      <group name="transform338" />
                    </group>
                    <group name="polySurface352" position={[0, -1.444, 0.565]}>
                      <group name="transform337" />
                    </group>
                    <group name="polySurface353" position={[0, -1.444, 0.565]}>
                      <group name="transform336" />
                    </group>
                    <group name="polySurface354" position={[0, -1.444, 0.565]}>
                      <group name="transform335" />
                    </group>
                    <group name="polySurface355" position={[0, -1.444, 0.565]}>
                      <group name="transform334" />
                    </group>
                    <group name="polySurface356" position={[0, -1.444, 0.565]}>
                      <group name="transform333" />
                    </group>
                    <group name="polySurface357" position={[0, -1.444, 0.565]}>
                      <group name="transform332" />
                    </group>
                    <group name="polySurface358" position={[0, -1.444, 0.565]}>
                      <group name="transform331" />
                    </group>
                    <group name="polySurface359" position={[0, -1.444, 0.565]}>
                      <group name="transform330" />
                    </group>
                    <group name="polySurface360" position={[0, -1.444, 0.565]}>
                      <group name="transform329" />
                    </group>
                    <group name="polySurface361" position={[0, -1.444, 0.565]}>
                      <group name="transform328" />
                    </group>
                    <group name="polySurface362" position={[0, -1.444, 0.565]}>
                      <group name="transform327" />
                    </group>
                    <group name="polySurface363" position={[0, -1.444, 0.565]}>
                      <group name="transform326" />
                    </group>
                    <group name="polySurface364" position={[0, -1.444, 0.565]}>
                      <group name="transform325" />
                    </group>
                    <group name="polySurface365" position={[0, -1.444, 0.565]}>
                      <group name="transform324" />
                    </group>
                    <group name="polySurface366" position={[0, -1.444, 0.565]}>
                      <group name="transform323" />
                    </group>
                    <group name="polySurface367" position={[0, -1.444, 0.565]}>
                      <group name="transform322" />
                    </group>
                    <group name="polySurface368" position={[0, -1.444, 0.565]}>
                      <group name="transform321" />
                    </group>
                    <group name="polySurface369" position={[0, -1.444, 0.565]}>
                      <group name="transform320" />
                    </group>
                    <group name="polySurface370" position={[0, -1.444, 0.565]}>
                      <group name="transform319" />
                    </group>
                    <group name="polySurface371" position={[0, -1.444, 0.565]}>
                      <group name="transform318" />
                    </group>
                    <group name="polySurface372" position={[0, -1.444, 0.565]}>
                      <group name="transform317" />
                    </group>
                    <group name="polySurface373" position={[0, -1.444, 0.565]}>
                      <group name="transform316" />
                    </group>
                    <group name="polySurface374" position={[0, -1.444, 0.565]}>
                      <group name="transform315" />
                    </group>
                    <group name="polySurface375" position={[0, -1.444, 0.565]}>
                      <group name="transform314" />
                    </group>
                    <group name="polySurface376" position={[0, -1.444, 0.565]}>
                      <group name="transform313" />
                    </group>
                    <group name="polySurface377" position={[0, -1.444, 0.565]}>
                      <group name="transform312" />
                    </group>
                    <group name="polySurface378" position={[0, -1.444, 0.565]}>
                      <group name="transform311" />
                    </group>
                    <group name="polySurface379" position={[0, -1.444, 0.565]}>
                      <group name="transform310" />
                    </group>
                    <group name="polySurface380" position={[0, -1.444, 0.565]}>
                      <group name="transform309" />
                    </group>
                    <group name="polySurface381" position={[0, -1.444, 0.565]}>
                      <group name="transform308" />
                    </group>
                    <group name="polySurface382" position={[0, -1.444, 0.565]}>
                      <group name="transform307" />
                    </group>
                    <group name="polySurface383" position={[0, -1.444, 0.565]}>
                      <group name="transform306" />
                    </group>
                    <group name="polySurface384" position={[0, -1.444, 0.565]}>
                      <group name="transform305" />
                    </group>
                    <group name="polySurface385" position={[0, -1.444, 0.565]}>
                      <group name="transform304" />
                    </group>
                    <group name="polySurface386" position={[0, -1.444, 0.565]}>
                      <group name="transform303" />
                    </group>
                    <group name="polySurface387" position={[0, -1.444, 0.565]}>
                      <group name="transform302" />
                    </group>
                    <group name="polySurface388" position={[0, -1.444, 0.565]}>
                      <group name="transform301" />
                    </group>
                    <group name="polySurface389" position={[0, -1.444, 0.565]}>
                      <group name="transform300" />
                    </group>
                    <group name="polySurface390" position={[0, -1.444, 0.565]}>
                      <group name="transform299" />
                    </group>
                    <group name="polySurface391" position={[0, -1.444, 0.565]}>
                      <group name="transform298" />
                    </group>
                    <group name="polySurface392" position={[0, -1.444, 0.565]}>
                      <group name="transform297" />
                    </group>
                    <group name="polySurface393" position={[0, -1.444, 0.565]}>
                      <group name="transform296" />
                    </group>
                    <group name="polySurface394" position={[0, -1.444, 0.565]}>
                      <group name="transform295" />
                    </group>
                    <group name="polySurface395" position={[0, -1.444, 0.565]}>
                      <group name="transform294" />
                    </group>
                    <group name="polySurface396" position={[0, -1.444, 0.565]}>
                      <group name="transform293" />
                    </group>
                    <group name="polySurface397" position={[0, -1.444, 0.565]}>
                      <group name="transform292" />
                    </group>
                    <group name="polySurface398" position={[0, -1.444, 0.565]}>
                      <group name="transform291" />
                    </group>
                    <group name="polySurface399" position={[0, -1.444, 0.565]}>
                      <group name="transform290" />
                    </group>
                    <group name="polySurface400" position={[0, -1.444, 0.565]}>
                      <group name="transform289" />
                    </group>
                    <group name="polySurface401" position={[0, -1.444, 0.565]}>
                      <group name="transform288" />
                    </group>
                    <group name="polySurface402" position={[0, -1.444, 0.565]}>
                      <group name="transform287" />
                    </group>
                    <group name="polySurface403" position={[0, -1.444, 0.565]}>
                      <group name="transform286" />
                    </group>
                    <group name="polySurface404" position={[0, -1.444, 0.565]}>
                      <group name="transform285" />
                    </group>
                    <group name="polySurface405" position={[0, -1.444, 0.565]}>
                      <group name="transform284" />
                    </group>
                    <group name="polySurface406" position={[0, -1.444, 0.565]}>
                      <group name="transform283" />
                    </group>
                    <group name="polySurface407" position={[0, -1.444, 0.565]}>
                      <group name="transform282" />
                    </group>
                    <group name="polySurface408" position={[0, -1.444, 0.565]}>
                      <group name="transform281" />
                    </group>
                    <group name="polySurface409" position={[0, -1.444, 0.565]}>
                      <group name="transform280" />
                    </group>
                    <group name="polySurface410" position={[0, -1.444, 0.565]}>
                      <group name="transform279" />
                    </group>
                    <group name="polySurface411" position={[0, -1.444, 0.565]}>
                      <group name="transform278" />
                    </group>
                    <group name="polySurface412" position={[0, -1.444, 0.565]}>
                      <group name="transform277" />
                    </group>
                    <group name="polySurface413" position={[0, -1.444, 0.565]}>
                      <group name="transform276" />
                    </group>
                    <group name="polySurface414" position={[0, -1.444, 0.565]}>
                      <group name="transform275" />
                    </group>
                    <group name="polySurface415" position={[0, -1.444, 0.565]}>
                      <group name="transform274" />
                    </group>
                    <group name="polySurface416" position={[0, -1.444, 0.565]}>
                      <group name="transform273" />
                    </group>
                    <group name="polySurface417" position={[0, -1.444, 0.565]}>
                      <group name="transform272" />
                    </group>
                    <group name="polySurface418" position={[0, -1.444, 0.565]}>
                      <group name="transform271" />
                    </group>
                    <group name="polySurface419" position={[0, -1.444, 0.565]}>
                      <group name="transform270" />
                    </group>
                    <group name="polySurface420" position={[0, -1.444, 0.565]}>
                      <group name="transform269" />
                    </group>
                    <group name="polySurface421" position={[0, -1.444, 0.565]}>
                      <group name="transform268" />
                    </group>
                    <group name="polySurface422" position={[0, -1.444, 0.565]}>
                      <group name="transform267" />
                    </group>
                    <group name="polySurface423" position={[0, -1.444, 0.565]}>
                      <group name="transform266" />
                    </group>
                    <group name="polySurface424" position={[0, -1.444, 0.565]}>
                      <group name="transform265" />
                    </group>
                    <group name="polySurface425" position={[0, -1.444, 0.565]}>
                      <group name="transform264" />
                    </group>
                    <group name="polySurface426" position={[0, -1.444, 0.565]}>
                      <group name="transform263" />
                    </group>
                    <group name="polySurface427" position={[0, -1.444, 0.565]}>
                      <group name="transform262" />
                    </group>
                    <group name="polySurface428" position={[0, -1.444, 0.565]}>
                      <group name="transform261" />
                    </group>
                    <group name="polySurface429" position={[0, -1.444, 0.565]}>
                      <group name="transform260" />
                    </group>
                    <group name="polySurface430" position={[0, -1.444, 0.565]}>
                      <group name="transform259" />
                    </group>
                    <group name="polySurface431" position={[0, -1.444, 0.565]}>
                      <group name="transform258" />
                    </group>
                    <group name="polySurface432" position={[0, -1.444, 0.565]}>
                      <group name="transform257" />
                    </group>
                    <group name="polySurface433" position={[0, -1.444, 0.565]}>
                      <group name="transform256" />
                    </group>
                    <group name="polySurface434" position={[0, -1.444, 0.565]}>
                      <group name="transform255" />
                    </group>
                    <group name="polySurface435" position={[0, -1.444, 0.565]}>
                      <group name="transform254" />
                    </group>
                    <group name="polySurface436" position={[0, -1.444, 0.565]}>
                      <group name="transform253" />
                    </group>
                    <group name="polySurface437" position={[0, -1.444, 0.565]}>
                      <group name="transform252" />
                    </group>
                    <group name="polySurface438" position={[0, -1.444, 0.565]}>
                      <group name="transform251" />
                    </group>
                    <group name="polySurface439" position={[0, -1.444, 0.565]}>
                      <group name="transform250" />
                    </group>
                    <group name="polySurface440" position={[0, -1.444, 0.565]}>
                      <group name="transform249" />
                    </group>
                    <group name="polySurface441" position={[0, -1.444, 0.565]}>
                      <group name="transform248" />
                    </group>
                    <group name="polySurface442" position={[0, -1.444, 0.565]}>
                      <group name="transform247" />
                    </group>
                    <group name="polySurface443" position={[0, -1.444, 0.565]}>
                      <group name="transform246" />
                    </group>
                    <group name="polySurface444" position={[0, -1.444, 0.565]}>
                      <group name="transform245" />
                    </group>
                    <group name="polySurface445" position={[0, -1.444, 0.565]}>
                      <group name="transform244" />
                    </group>
                    <group name="polySurface446" position={[0, -1.444, 0.565]}>
                      <group name="transform243" />
                    </group>
                    <group name="polySurface447" position={[0, -1.444, 0.565]}>
                      <group name="transform242" />
                    </group>
                    <group name="polySurface448" position={[0, -1.444, 0.565]}>
                      <group name="transform241" />
                    </group>
                    <group name="polySurface449" position={[0, -1.444, 0.565]}>
                      <group name="transform240" />
                    </group>
                    <group name="polySurface450" position={[0, -1.444, 0.565]}>
                      <group name="transform239" />
                    </group>
                    <group name="polySurface451" position={[0, -1.444, 0.565]}>
                      <group name="transform238" />
                    </group>
                    <group name="polySurface452" position={[0, -1.444, 0.565]}>
                      <group name="transform237" />
                    </group>
                    <group name="polySurface453" position={[0, -1.444, 0.565]}>
                      <group name="transform236" />
                    </group>
                    <group name="transform235" position={[0, -1.444, 0.565]} />
                  </group>
                  <group name="pCube90" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.lambert1} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/piano_animation.glb')

export default Piano;