/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 piano.glb 
Author: ronedo (https://sketchfab.com/ronedo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pianist-at-the-grand-piano-animated-4ecb1d35cee44352afe03d03289532e8
Title: Pianist at the Grand Piano (Animated)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

function Piano(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/piano.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions);
      useEffect(() => {
        actions['Armature|mixamo.com|Layer0']?.play()
      }, [actions])
  return (
    <group ref={group} {...props} dispose={null} scale={0.7}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_10" position={[2.535, 0.013, 0.579]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Collada_visual_scene_group_9" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="chair_1">
                    <group name="defaultMaterial_0" position={[0.06, -0.071, 0.168]}>
                      <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['chair_mt.001']} />
                    </group>
                  </group>
                  <group name="logo_3">
                    <group name="defaultMaterial007_2" position={[-0.256, -0.071, 0.168]}>
                      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['piano_logo_mt.001']} />
                    </group>
                  </group>
                  <group name="piano_8">
                    <group name="defaultMaterial001_4">
                      <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['piano_velvet_mt.001']} />
                    </group>
                    <group name="defaultMaterial003_5">
                      <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['piano_metal_mt.001']} />
                    </group>
                    <group name="defaultMaterial005_6">
                      <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['piano_wood_mt.001']} />
                    </group>
                    <group name="defaultMaterial006_7">
                      <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['piano_body_mt.001']} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="Armature_85" position={[2.73, -0.026, 2.494]} rotation={[Math.PI / 2, 0, 3.033]} scale={[-0.02, 0.026, 0.026]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Ch33_Belt_76" />
                  <group name="Ch33_Body_77" />
                  <group name="Ch33_Eyelashes_78" />
                  <group name="Ch33_Hair_79" />
                  <group name="Ch33_Pants_80" />
                  <group name="Ch33_Shirt_81" />
                  <group name="Ch33_Shoes_82" />
                  <group name="Ch33_Suit_83" />
                  <group name="Ch33_Tie_84" />
                  <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_24.skeleton} />
                  <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_26.skeleton} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Ch33_hair.001']} skeleton={nodes.Object_28.skeleton} />
                  <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Ch33_hair.001']} skeleton={nodes.Object_30.skeleton} />
                  <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_32.skeleton} />
                  <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_34.skeleton} />
                  <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_36.skeleton} />
                  <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_38.skeleton} />
                  <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Ch33_body.001']} skeleton={nodes.Object_40.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/piano.glb')

export default Piano;
