/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plank.glb 
Author: Holly_Climpson (https://sketchfab.com/Holly_Climpson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plank-308729005e2849c4bf9f61f87650b48c
Title: Plank
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Plank(props) {
	const { nodes, materials } = useGLTF("/models/plank.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={0.21}>
				<mesh geometry={nodes.pCube11_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, 0]} scale={[22.24, 0.546, 2.986]} />
			</group>
		</group>
	);
}

useGLTF.preload("/models/plank.glb");

export default Plank;
