/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 singing.glb 
Author: Joe chakrapong (https://sketchfab.com/chakrapong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/singing-b759dcc164d44be3984e900e0665e5f5
Title: Singing
*/

import React, { use, useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

 function Singing(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/singing.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(() => {
    actions['mixamo.com'].play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="0e87bb3611874ccc87922f118a6821f1fbx" rotation={[Math.PI / 2, 4, 0]} scale={0.055}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_8" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_10" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_12" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_14" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_16" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_18" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_20" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_22" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="Object_24" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id717" position={[0.052, 43.25, 15.364]} rotation={[-1.646, 0, 0]} scale={[27.464, 27.467, 27.908]}>
                    <group name="node_id718" position={[0, 0, 0.156]} rotation={[0.409, 0, 0]}>
                      <group name="node_id719" position={[0, 0, 0.123]} rotation={[-0.327, 0, 0]}>
                        <group name="node_id720" position={[0, -0.037, 0.226]} rotation={[-0.007, 0, 0]} />
                        <group name="node_id721" position={[0.03, -0.082, 0.088]} rotation={[-0.007, 0, 0]} />
                        <group name="node_id722" position={[-0.03, -0.082, 0.088]} rotation={[-0.007, 0, 0]} />
                      </group>
                    </group>
                    <group name="node_id723" position={[0.047, 0.006, 0.141]} rotation={[-2.929, 1.53, -1.794]}>
                      <group name="node_id724" position={[0, 0, 0.119]} rotation={[0.995, 0.144, 0.019]} />
                    </group>
                    <group name="node_id747" position={[-0.047, 0.006, 0.141]} rotation={[-2.929, -1.53, 1.794]}>
                      <group name="node_id748" position={[0, 0, 0.119]} rotation={[0.995, -0.144, -0.019]} />
                    </group>
                  </group>
                  <group name="node_id782" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id785" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id788" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id791" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id794" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id797" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id800" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id803" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id806" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <group name="node_id809" position={[0.052, 5.084, 15.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.464, 27.464, 27.91]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_1} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_2} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material_3} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material_4} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material_5} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material_6} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Material_7} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Material_8} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Material_9} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Material_10} skeleton={nodes.Object_25.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/singing.glb')

export default Singing;
