/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 synth.glb 
Author: Gerhald (https://sketchfab.com/Gerhald)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/synthesizer-free-2e326ce54187420c8598fa0404697bdc
Title: Synthesizer free
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
function Synth(props) {
	const { nodes, materials } = useGLTF("/models/synth.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={0.02}>
				<mesh geometry={nodes.Synthesizer_Piano_Synthesizer_Piano_0.geometry} material={materials.Synthesizer_Piano} position={[0, -0.632, 0]} />
				<mesh geometry={nodes.Synthesizer_Stand_Synthesizer_Stand_0.geometry} material={materials.Synthesizer_Stand} position={[0, -0.632, 0]} />
			</group>
		</group>
	);
}

useGLTF.preload("/models/synth.glb");

export default Synth;
