/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wood.glb 
Author: torchwurm (https://sketchfab.com/torchwurm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-ground-texture-8c950ceace1d4cac8923cf00bb203571
Title: Wood Ground Texture
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Wood(props) {
	const { nodes, materials } = useGLTF("/models/wood.glb");
	return (
		<group {...props} dispose={null} scale={3.3}>
			<mesh geometry={nodes.Plane_1.geometry} material={materials["Material.001"]} rotation={[-Math.PI / 2, 0, 0]} />
		</group>
	);
}

useGLTF.preload("/models/wood.glb");

export default Wood;
